package com.hiaward.cl.oms.client;

import com.hiaward.cl.oms.entity.DeviceModelIdcInfo;
import com.hiaward.cl.oms.entity.DeviceModelIdcInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceModelIdcInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	int countByExample(DeviceModelIdcInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	int deleteByExample(DeviceModelIdcInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	int deleteByPrimaryKey(String idcNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	int insert(DeviceModelIdcInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	int insertSelective(DeviceModelIdcInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	List<DeviceModelIdcInfo> selectByExample(DeviceModelIdcInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	DeviceModelIdcInfo selectByPrimaryKey(String idcNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	int updateByExampleSelective(@Param("record") DeviceModelIdcInfo record,
			@Param("example") DeviceModelIdcInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	int updateByExample(@Param("record") DeviceModelIdcInfo record,
			@Param("example") DeviceModelIdcInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	int updateByPrimaryKeySelective(DeviceModelIdcInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	int updateByPrimaryKey(DeviceModelIdcInfo record);
}