package com.hiaward.cl.oms.client;

import com.hiaward.cl.oms.entity.DeviceFaultInfo;
import com.hiaward.cl.oms.entity.DeviceFaultInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceFaultInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	int countByExample(DeviceFaultInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	int deleteByExample(DeviceFaultInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	int deleteByPrimaryKey(String faultNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	int insert(DeviceFaultInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	int insertSelective(DeviceFaultInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	List<DeviceFaultInfo> selectByExample(DeviceFaultInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	DeviceFaultInfo selectByPrimaryKey(String faultNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	int updateByExampleSelective(@Param("record") DeviceFaultInfo record,
			@Param("example") DeviceFaultInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	int updateByExample(@Param("record") DeviceFaultInfo record, @Param("example") DeviceFaultInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	int updateByPrimaryKeySelective(DeviceFaultInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	int updateByPrimaryKey(DeviceFaultInfo record);
}