package com.hiaward.cl.oms.client;

import com.hiaward.cl.oms.entity.DeviceTradeInfo;
import com.hiaward.cl.oms.entity.DeviceTradeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceTradeInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	int countByExample(DeviceTradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	int deleteByExample(DeviceTradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	int deleteByPrimaryKey(String tradeNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	int insert(DeviceTradeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	int insertSelective(DeviceTradeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	List<DeviceTradeInfo> selectByExample(DeviceTradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	DeviceTradeInfo selectByPrimaryKey(String tradeNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	int updateByExampleSelective(@Param("record") DeviceTradeInfo record,
			@Param("example") DeviceTradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	int updateByExample(@Param("record") DeviceTradeInfo record, @Param("example") DeviceTradeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	int updateByPrimaryKeySelective(DeviceTradeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	int updateByPrimaryKey(DeviceTradeInfo record);
}