package com.hiaward.cl.oms.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeviceInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public DeviceInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andDeviceNoIsNull() {
			addCriterion("DEVICE_NO is null");
			return (Criteria) this;
		}

		public Criteria andDeviceNoIsNotNull() {
			addCriterion("DEVICE_NO is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceNoEqualTo(String value) {
			addCriterion("DEVICE_NO =", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotEqualTo(String value) {
			addCriterion("DEVICE_NO <>", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoGreaterThan(String value) {
			addCriterion("DEVICE_NO >", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoGreaterThanOrEqualTo(String value) {
			addCriterion("DEVICE_NO >=", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoLessThan(String value) {
			addCriterion("DEVICE_NO <", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoLessThanOrEqualTo(String value) {
			addCriterion("DEVICE_NO <=", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoLike(String value) {
			addCriterion("DEVICE_NO like", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotLike(String value) {
			addCriterion("DEVICE_NO not like", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoIn(List<String> values) {
			addCriterion("DEVICE_NO in", values, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotIn(List<String> values) {
			addCriterion("DEVICE_NO not in", values, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoBetween(String value1, String value2) {
			addCriterion("DEVICE_NO between", value1, value2, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotBetween(String value1, String value2) {
			addCriterion("DEVICE_NO not between", value1, value2, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andIpIsNull() {
			addCriterion("IP is null");
			return (Criteria) this;
		}

		public Criteria andIpIsNotNull() {
			addCriterion("IP is not null");
			return (Criteria) this;
		}

		public Criteria andIpEqualTo(String value) {
			addCriterion("IP =", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotEqualTo(String value) {
			addCriterion("IP <>", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThan(String value) {
			addCriterion("IP >", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThanOrEqualTo(String value) {
			addCriterion("IP >=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThan(String value) {
			addCriterion("IP <", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThanOrEqualTo(String value) {
			addCriterion("IP <=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLike(String value) {
			addCriterion("IP like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotLike(String value) {
			addCriterion("IP not like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpIn(List<String> values) {
			addCriterion("IP in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotIn(List<String> values) {
			addCriterion("IP not in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpBetween(String value1, String value2) {
			addCriterion("IP between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotBetween(String value1, String value2) {
			addCriterion("IP not between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andTellerNoIsNull() {
			addCriterion("TELLER_NO is null");
			return (Criteria) this;
		}

		public Criteria andTellerNoIsNotNull() {
			addCriterion("TELLER_NO is not null");
			return (Criteria) this;
		}

		public Criteria andTellerNoEqualTo(String value) {
			addCriterion("TELLER_NO =", value, "tellerNo");
			return (Criteria) this;
		}

		public Criteria andTellerNoNotEqualTo(String value) {
			addCriterion("TELLER_NO <>", value, "tellerNo");
			return (Criteria) this;
		}

		public Criteria andTellerNoGreaterThan(String value) {
			addCriterion("TELLER_NO >", value, "tellerNo");
			return (Criteria) this;
		}

		public Criteria andTellerNoGreaterThanOrEqualTo(String value) {
			addCriterion("TELLER_NO >=", value, "tellerNo");
			return (Criteria) this;
		}

		public Criteria andTellerNoLessThan(String value) {
			addCriterion("TELLER_NO <", value, "tellerNo");
			return (Criteria) this;
		}

		public Criteria andTellerNoLessThanOrEqualTo(String value) {
			addCriterion("TELLER_NO <=", value, "tellerNo");
			return (Criteria) this;
		}

		public Criteria andTellerNoLike(String value) {
			addCriterion("TELLER_NO like", value, "tellerNo");
			return (Criteria) this;
		}

		public Criteria andTellerNoNotLike(String value) {
			addCriterion("TELLER_NO not like", value, "tellerNo");
			return (Criteria) this;
		}

		public Criteria andTellerNoIn(List<String> values) {
			addCriterion("TELLER_NO in", values, "tellerNo");
			return (Criteria) this;
		}

		public Criteria andTellerNoNotIn(List<String> values) {
			addCriterion("TELLER_NO not in", values, "tellerNo");
			return (Criteria) this;
		}

		public Criteria andTellerNoBetween(String value1, String value2) {
			addCriterion("TELLER_NO between", value1, value2, "tellerNo");
			return (Criteria) this;
		}

		public Criteria andTellerNoNotBetween(String value1, String value2) {
			addCriterion("TELLER_NO not between", value1, value2, "tellerNo");
			return (Criteria) this;
		}

		public Criteria andSerNumIsNull() {
			addCriterion("SER_NUM is null");
			return (Criteria) this;
		}

		public Criteria andSerNumIsNotNull() {
			addCriterion("SER_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andSerNumEqualTo(String value) {
			addCriterion("SER_NUM =", value, "serNum");
			return (Criteria) this;
		}

		public Criteria andSerNumNotEqualTo(String value) {
			addCriterion("SER_NUM <>", value, "serNum");
			return (Criteria) this;
		}

		public Criteria andSerNumGreaterThan(String value) {
			addCriterion("SER_NUM >", value, "serNum");
			return (Criteria) this;
		}

		public Criteria andSerNumGreaterThanOrEqualTo(String value) {
			addCriterion("SER_NUM >=", value, "serNum");
			return (Criteria) this;
		}

		public Criteria andSerNumLessThan(String value) {
			addCriterion("SER_NUM <", value, "serNum");
			return (Criteria) this;
		}

		public Criteria andSerNumLessThanOrEqualTo(String value) {
			addCriterion("SER_NUM <=", value, "serNum");
			return (Criteria) this;
		}

		public Criteria andSerNumLike(String value) {
			addCriterion("SER_NUM like", value, "serNum");
			return (Criteria) this;
		}

		public Criteria andSerNumNotLike(String value) {
			addCriterion("SER_NUM not like", value, "serNum");
			return (Criteria) this;
		}

		public Criteria andSerNumIn(List<String> values) {
			addCriterion("SER_NUM in", values, "serNum");
			return (Criteria) this;
		}

		public Criteria andSerNumNotIn(List<String> values) {
			addCriterion("SER_NUM not in", values, "serNum");
			return (Criteria) this;
		}

		public Criteria andSerNumBetween(String value1, String value2) {
			addCriterion("SER_NUM between", value1, value2, "serNum");
			return (Criteria) this;
		}

		public Criteria andSerNumNotBetween(String value1, String value2) {
			addCriterion("SER_NUM not between", value1, value2, "serNum");
			return (Criteria) this;
		}

		public Criteria andManufacturerIsNull() {
			addCriterion("MANUFACTURER is null");
			return (Criteria) this;
		}

		public Criteria andManufacturerIsNotNull() {
			addCriterion("MANUFACTURER is not null");
			return (Criteria) this;
		}

		public Criteria andManufacturerEqualTo(String value) {
			addCriterion("MANUFACTURER =", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerNotEqualTo(String value) {
			addCriterion("MANUFACTURER <>", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerGreaterThan(String value) {
			addCriterion("MANUFACTURER >", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerGreaterThanOrEqualTo(String value) {
			addCriterion("MANUFACTURER >=", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerLessThan(String value) {
			addCriterion("MANUFACTURER <", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerLessThanOrEqualTo(String value) {
			addCriterion("MANUFACTURER <=", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerLike(String value) {
			addCriterion("MANUFACTURER like", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerNotLike(String value) {
			addCriterion("MANUFACTURER not like", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerIn(List<String> values) {
			addCriterion("MANUFACTURER in", values, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerNotIn(List<String> values) {
			addCriterion("MANUFACTURER not in", values, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerBetween(String value1, String value2) {
			addCriterion("MANUFACTURER between", value1, value2, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerNotBetween(String value1, String value2) {
			addCriterion("MANUFACTURER not between", value1, value2, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeIsNull() {
			addCriterion("DEVICE_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeIsNotNull() {
			addCriterion("DEVICE_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeEqualTo(String value) {
			addCriterion("DEVICE_TYPE =", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeNotEqualTo(String value) {
			addCriterion("DEVICE_TYPE <>", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeGreaterThan(String value) {
			addCriterion("DEVICE_TYPE >", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeGreaterThanOrEqualTo(String value) {
			addCriterion("DEVICE_TYPE >=", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeLessThan(String value) {
			addCriterion("DEVICE_TYPE <", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeLessThanOrEqualTo(String value) {
			addCriterion("DEVICE_TYPE <=", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeLike(String value) {
			addCriterion("DEVICE_TYPE like", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeNotLike(String value) {
			addCriterion("DEVICE_TYPE not like", value, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeIn(List<String> values) {
			addCriterion("DEVICE_TYPE in", values, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeNotIn(List<String> values) {
			addCriterion("DEVICE_TYPE not in", values, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeBetween(String value1, String value2) {
			addCriterion("DEVICE_TYPE between", value1, value2, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceTypeNotBetween(String value1, String value2) {
			addCriterion("DEVICE_TYPE not between", value1, value2, "deviceType");
			return (Criteria) this;
		}

		public Criteria andDeviceModelIsNull() {
			addCriterion("DEVICE_MODEL is null");
			return (Criteria) this;
		}

		public Criteria andDeviceModelIsNotNull() {
			addCriterion("DEVICE_MODEL is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceModelEqualTo(String value) {
			addCriterion("DEVICE_MODEL =", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelNotEqualTo(String value) {
			addCriterion("DEVICE_MODEL <>", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelGreaterThan(String value) {
			addCriterion("DEVICE_MODEL >", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelGreaterThanOrEqualTo(String value) {
			addCriterion("DEVICE_MODEL >=", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelLessThan(String value) {
			addCriterion("DEVICE_MODEL <", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelLessThanOrEqualTo(String value) {
			addCriterion("DEVICE_MODEL <=", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelLike(String value) {
			addCriterion("DEVICE_MODEL like", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelNotLike(String value) {
			addCriterion("DEVICE_MODEL not like", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelIn(List<String> values) {
			addCriterion("DEVICE_MODEL in", values, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelNotIn(List<String> values) {
			addCriterion("DEVICE_MODEL not in", values, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelBetween(String value1, String value2) {
			addCriterion("DEVICE_MODEL between", value1, value2, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelNotBetween(String value1, String value2) {
			addCriterion("DEVICE_MODEL not between", value1, value2, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceStateIsNull() {
			addCriterion("DEVICE_STATE is null");
			return (Criteria) this;
		}

		public Criteria andDeviceStateIsNotNull() {
			addCriterion("DEVICE_STATE is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceStateEqualTo(String value) {
			addCriterion("DEVICE_STATE =", value, "deviceState");
			return (Criteria) this;
		}

		public Criteria andDeviceStateNotEqualTo(String value) {
			addCriterion("DEVICE_STATE <>", value, "deviceState");
			return (Criteria) this;
		}

		public Criteria andDeviceStateGreaterThan(String value) {
			addCriterion("DEVICE_STATE >", value, "deviceState");
			return (Criteria) this;
		}

		public Criteria andDeviceStateGreaterThanOrEqualTo(String value) {
			addCriterion("DEVICE_STATE >=", value, "deviceState");
			return (Criteria) this;
		}

		public Criteria andDeviceStateLessThan(String value) {
			addCriterion("DEVICE_STATE <", value, "deviceState");
			return (Criteria) this;
		}

		public Criteria andDeviceStateLessThanOrEqualTo(String value) {
			addCriterion("DEVICE_STATE <=", value, "deviceState");
			return (Criteria) this;
		}

		public Criteria andDeviceStateLike(String value) {
			addCriterion("DEVICE_STATE like", value, "deviceState");
			return (Criteria) this;
		}

		public Criteria andDeviceStateNotLike(String value) {
			addCriterion("DEVICE_STATE not like", value, "deviceState");
			return (Criteria) this;
		}

		public Criteria andDeviceStateIn(List<String> values) {
			addCriterion("DEVICE_STATE in", values, "deviceState");
			return (Criteria) this;
		}

		public Criteria andDeviceStateNotIn(List<String> values) {
			addCriterion("DEVICE_STATE not in", values, "deviceState");
			return (Criteria) this;
		}

		public Criteria andDeviceStateBetween(String value1, String value2) {
			addCriterion("DEVICE_STATE between", value1, value2, "deviceState");
			return (Criteria) this;
		}

		public Criteria andDeviceStateNotBetween(String value1, String value2) {
			addCriterion("DEVICE_STATE not between", value1, value2, "deviceState");
			return (Criteria) this;
		}

		public Criteria andSerStateIsNull() {
			addCriterion("SER_STATE is null");
			return (Criteria) this;
		}

		public Criteria andSerStateIsNotNull() {
			addCriterion("SER_STATE is not null");
			return (Criteria) this;
		}

		public Criteria andSerStateEqualTo(String value) {
			addCriterion("SER_STATE =", value, "serState");
			return (Criteria) this;
		}

		public Criteria andSerStateNotEqualTo(String value) {
			addCriterion("SER_STATE <>", value, "serState");
			return (Criteria) this;
		}

		public Criteria andSerStateGreaterThan(String value) {
			addCriterion("SER_STATE >", value, "serState");
			return (Criteria) this;
		}

		public Criteria andSerStateGreaterThanOrEqualTo(String value) {
			addCriterion("SER_STATE >=", value, "serState");
			return (Criteria) this;
		}

		public Criteria andSerStateLessThan(String value) {
			addCriterion("SER_STATE <", value, "serState");
			return (Criteria) this;
		}

		public Criteria andSerStateLessThanOrEqualTo(String value) {
			addCriterion("SER_STATE <=", value, "serState");
			return (Criteria) this;
		}

		public Criteria andSerStateLike(String value) {
			addCriterion("SER_STATE like", value, "serState");
			return (Criteria) this;
		}

		public Criteria andSerStateNotLike(String value) {
			addCriterion("SER_STATE not like", value, "serState");
			return (Criteria) this;
		}

		public Criteria andSerStateIn(List<String> values) {
			addCriterion("SER_STATE in", values, "serState");
			return (Criteria) this;
		}

		public Criteria andSerStateNotIn(List<String> values) {
			addCriterion("SER_STATE not in", values, "serState");
			return (Criteria) this;
		}

		public Criteria andSerStateBetween(String value1, String value2) {
			addCriterion("SER_STATE between", value1, value2, "serState");
			return (Criteria) this;
		}

		public Criteria andSerStateNotBetween(String value1, String value2) {
			addCriterion("SER_STATE not between", value1, value2, "serState");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("STATE is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("STATE is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(String value) {
			addCriterion("STATE =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(String value) {
			addCriterion("STATE <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(String value) {
			addCriterion("STATE >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(String value) {
			addCriterion("STATE >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(String value) {
			addCriterion("STATE <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(String value) {
			addCriterion("STATE <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLike(String value) {
			addCriterion("STATE like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotLike(String value) {
			addCriterion("STATE not like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<String> values) {
			addCriterion("STATE in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<String> values) {
			addCriterion("STATE not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(String value1, String value2) {
			addCriterion("STATE between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(String value1, String value2) {
			addCriterion("STATE not between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andRegDateIsNull() {
			addCriterion("REG_DATE is null");
			return (Criteria) this;
		}

		public Criteria andRegDateIsNotNull() {
			addCriterion("REG_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andRegDateEqualTo(Date value) {
			addCriterion("REG_DATE =", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotEqualTo(Date value) {
			addCriterion("REG_DATE <>", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateGreaterThan(Date value) {
			addCriterion("REG_DATE >", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateGreaterThanOrEqualTo(Date value) {
			addCriterion("REG_DATE >=", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateLessThan(Date value) {
			addCriterion("REG_DATE <", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateLessThanOrEqualTo(Date value) {
			addCriterion("REG_DATE <=", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateIn(List<Date> values) {
			addCriterion("REG_DATE in", values, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotIn(List<Date> values) {
			addCriterion("REG_DATE not in", values, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateBetween(Date value1, Date value2) {
			addCriterion("REG_DATE between", value1, value2, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotBetween(Date value1, Date value2) {
			addCriterion("REG_DATE not between", value1, value2, "regDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table device_info
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 14 15:32:58 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}