package com.hiaward.cl.oms.entity;

import java.util.ArrayList;
import java.util.List;

public class DeviceModelIdcInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public DeviceModelIdcInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdcNoIsNull() {
			addCriterion("IDC_NO is null");
			return (Criteria) this;
		}

		public Criteria andIdcNoIsNotNull() {
			addCriterion("IDC_NO is not null");
			return (Criteria) this;
		}

		public Criteria andIdcNoEqualTo(String value) {
			addCriterion("IDC_NO =", value, "idcNo");
			return (Criteria) this;
		}

		public Criteria andIdcNoNotEqualTo(String value) {
			addCriterion("IDC_NO <>", value, "idcNo");
			return (Criteria) this;
		}

		public Criteria andIdcNoGreaterThan(String value) {
			addCriterion("IDC_NO >", value, "idcNo");
			return (Criteria) this;
		}

		public Criteria andIdcNoGreaterThanOrEqualTo(String value) {
			addCriterion("IDC_NO >=", value, "idcNo");
			return (Criteria) this;
		}

		public Criteria andIdcNoLessThan(String value) {
			addCriterion("IDC_NO <", value, "idcNo");
			return (Criteria) this;
		}

		public Criteria andIdcNoLessThanOrEqualTo(String value) {
			addCriterion("IDC_NO <=", value, "idcNo");
			return (Criteria) this;
		}

		public Criteria andIdcNoLike(String value) {
			addCriterion("IDC_NO like", value, "idcNo");
			return (Criteria) this;
		}

		public Criteria andIdcNoNotLike(String value) {
			addCriterion("IDC_NO not like", value, "idcNo");
			return (Criteria) this;
		}

		public Criteria andIdcNoIn(List<String> values) {
			addCriterion("IDC_NO in", values, "idcNo");
			return (Criteria) this;
		}

		public Criteria andIdcNoNotIn(List<String> values) {
			addCriterion("IDC_NO not in", values, "idcNo");
			return (Criteria) this;
		}

		public Criteria andIdcNoBetween(String value1, String value2) {
			addCriterion("IDC_NO between", value1, value2, "idcNo");
			return (Criteria) this;
		}

		public Criteria andIdcNoNotBetween(String value1, String value2) {
			addCriterion("IDC_NO not between", value1, value2, "idcNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoIsNull() {
			addCriterion("DEVICE_NO is null");
			return (Criteria) this;
		}

		public Criteria andDeviceNoIsNotNull() {
			addCriterion("DEVICE_NO is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceNoEqualTo(String value) {
			addCriterion("DEVICE_NO =", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotEqualTo(String value) {
			addCriterion("DEVICE_NO <>", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoGreaterThan(String value) {
			addCriterion("DEVICE_NO >", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoGreaterThanOrEqualTo(String value) {
			addCriterion("DEVICE_NO >=", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoLessThan(String value) {
			addCriterion("DEVICE_NO <", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoLessThanOrEqualTo(String value) {
			addCriterion("DEVICE_NO <=", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoLike(String value) {
			addCriterion("DEVICE_NO like", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotLike(String value) {
			addCriterion("DEVICE_NO not like", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoIn(List<String> values) {
			addCriterion("DEVICE_NO in", values, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotIn(List<String> values) {
			addCriterion("DEVICE_NO not in", values, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoBetween(String value1, String value2) {
			addCriterion("DEVICE_NO between", value1, value2, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotBetween(String value1, String value2) {
			addCriterion("DEVICE_NO not between", value1, value2, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andIdcModelIsNull() {
			addCriterion("IDC_MODEL is null");
			return (Criteria) this;
		}

		public Criteria andIdcModelIsNotNull() {
			addCriterion("IDC_MODEL is not null");
			return (Criteria) this;
		}

		public Criteria andIdcModelEqualTo(String value) {
			addCriterion("IDC_MODEL =", value, "idcModel");
			return (Criteria) this;
		}

		public Criteria andIdcModelNotEqualTo(String value) {
			addCriterion("IDC_MODEL <>", value, "idcModel");
			return (Criteria) this;
		}

		public Criteria andIdcModelGreaterThan(String value) {
			addCriterion("IDC_MODEL >", value, "idcModel");
			return (Criteria) this;
		}

		public Criteria andIdcModelGreaterThanOrEqualTo(String value) {
			addCriterion("IDC_MODEL >=", value, "idcModel");
			return (Criteria) this;
		}

		public Criteria andIdcModelLessThan(String value) {
			addCriterion("IDC_MODEL <", value, "idcModel");
			return (Criteria) this;
		}

		public Criteria andIdcModelLessThanOrEqualTo(String value) {
			addCriterion("IDC_MODEL <=", value, "idcModel");
			return (Criteria) this;
		}

		public Criteria andIdcModelLike(String value) {
			addCriterion("IDC_MODEL like", value, "idcModel");
			return (Criteria) this;
		}

		public Criteria andIdcModelNotLike(String value) {
			addCriterion("IDC_MODEL not like", value, "idcModel");
			return (Criteria) this;
		}

		public Criteria andIdcModelIn(List<String> values) {
			addCriterion("IDC_MODEL in", values, "idcModel");
			return (Criteria) this;
		}

		public Criteria andIdcModelNotIn(List<String> values) {
			addCriterion("IDC_MODEL not in", values, "idcModel");
			return (Criteria) this;
		}

		public Criteria andIdcModelBetween(String value1, String value2) {
			addCriterion("IDC_MODEL between", value1, value2, "idcModel");
			return (Criteria) this;
		}

		public Criteria andIdcModelNotBetween(String value1, String value2) {
			addCriterion("IDC_MODEL not between", value1, value2, "idcModel");
			return (Criteria) this;
		}

		public Criteria andCardStateIsNull() {
			addCriterion("CARD_STATE is null");
			return (Criteria) this;
		}

		public Criteria andCardStateIsNotNull() {
			addCriterion("CARD_STATE is not null");
			return (Criteria) this;
		}

		public Criteria andCardStateEqualTo(String value) {
			addCriterion("CARD_STATE =", value, "cardState");
			return (Criteria) this;
		}

		public Criteria andCardStateNotEqualTo(String value) {
			addCriterion("CARD_STATE <>", value, "cardState");
			return (Criteria) this;
		}

		public Criteria andCardStateGreaterThan(String value) {
			addCriterion("CARD_STATE >", value, "cardState");
			return (Criteria) this;
		}

		public Criteria andCardStateGreaterThanOrEqualTo(String value) {
			addCriterion("CARD_STATE >=", value, "cardState");
			return (Criteria) this;
		}

		public Criteria andCardStateLessThan(String value) {
			addCriterion("CARD_STATE <", value, "cardState");
			return (Criteria) this;
		}

		public Criteria andCardStateLessThanOrEqualTo(String value) {
			addCriterion("CARD_STATE <=", value, "cardState");
			return (Criteria) this;
		}

		public Criteria andCardStateLike(String value) {
			addCriterion("CARD_STATE like", value, "cardState");
			return (Criteria) this;
		}

		public Criteria andCardStateNotLike(String value) {
			addCriterion("CARD_STATE not like", value, "cardState");
			return (Criteria) this;
		}

		public Criteria andCardStateIn(List<String> values) {
			addCriterion("CARD_STATE in", values, "cardState");
			return (Criteria) this;
		}

		public Criteria andCardStateNotIn(List<String> values) {
			addCriterion("CARD_STATE not in", values, "cardState");
			return (Criteria) this;
		}

		public Criteria andCardStateBetween(String value1, String value2) {
			addCriterion("CARD_STATE between", value1, value2, "cardState");
			return (Criteria) this;
		}

		public Criteria andCardStateNotBetween(String value1, String value2) {
			addCriterion("CARD_STATE not between", value1, value2, "cardState");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxIsNull() {
			addCriterion("RECOVERY_BOX is null");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxIsNotNull() {
			addCriterion("RECOVERY_BOX is not null");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxEqualTo(String value) {
			addCriterion("RECOVERY_BOX =", value, "recoveryBox");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxNotEqualTo(String value) {
			addCriterion("RECOVERY_BOX <>", value, "recoveryBox");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxGreaterThan(String value) {
			addCriterion("RECOVERY_BOX >", value, "recoveryBox");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxGreaterThanOrEqualTo(String value) {
			addCriterion("RECOVERY_BOX >=", value, "recoveryBox");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxLessThan(String value) {
			addCriterion("RECOVERY_BOX <", value, "recoveryBox");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxLessThanOrEqualTo(String value) {
			addCriterion("RECOVERY_BOX <=", value, "recoveryBox");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxLike(String value) {
			addCriterion("RECOVERY_BOX like", value, "recoveryBox");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxNotLike(String value) {
			addCriterion("RECOVERY_BOX not like", value, "recoveryBox");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxIn(List<String> values) {
			addCriterion("RECOVERY_BOX in", values, "recoveryBox");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxNotIn(List<String> values) {
			addCriterion("RECOVERY_BOX not in", values, "recoveryBox");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxBetween(String value1, String value2) {
			addCriterion("RECOVERY_BOX between", value1, value2, "recoveryBox");
			return (Criteria) this;
		}

		public Criteria andRecoveryBoxNotBetween(String value1, String value2) {
			addCriterion("RECOVERY_BOX not between", value1, value2, "recoveryBox");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportIsNull() {
			addCriterion("Security_support is null");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportIsNotNull() {
			addCriterion("Security_support is not null");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportEqualTo(String value) {
			addCriterion("Security_support =", value, "securitySupport");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportNotEqualTo(String value) {
			addCriterion("Security_support <>", value, "securitySupport");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportGreaterThan(String value) {
			addCriterion("Security_support >", value, "securitySupport");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportGreaterThanOrEqualTo(String value) {
			addCriterion("Security_support >=", value, "securitySupport");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportLessThan(String value) {
			addCriterion("Security_support <", value, "securitySupport");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportLessThanOrEqualTo(String value) {
			addCriterion("Security_support <=", value, "securitySupport");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportLike(String value) {
			addCriterion("Security_support like", value, "securitySupport");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportNotLike(String value) {
			addCriterion("Security_support not like", value, "securitySupport");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportIn(List<String> values) {
			addCriterion("Security_support in", values, "securitySupport");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportNotIn(List<String> values) {
			addCriterion("Security_support not in", values, "securitySupport");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportBetween(String value1, String value2) {
			addCriterion("Security_support between", value1, value2, "securitySupport");
			return (Criteria) this;
		}

		public Criteria andSecuritySupportNotBetween(String value1, String value2) {
			addCriterion("Security_support not between", value1, value2, "securitySupport");
			return (Criteria) this;
		}

		public Criteria andScardNumIsNull() {
			addCriterion("scard_num is null");
			return (Criteria) this;
		}

		public Criteria andScardNumIsNotNull() {
			addCriterion("scard_num is not null");
			return (Criteria) this;
		}

		public Criteria andScardNumEqualTo(String value) {
			addCriterion("scard_num =", value, "scardNum");
			return (Criteria) this;
		}

		public Criteria andScardNumNotEqualTo(String value) {
			addCriterion("scard_num <>", value, "scardNum");
			return (Criteria) this;
		}

		public Criteria andScardNumGreaterThan(String value) {
			addCriterion("scard_num >", value, "scardNum");
			return (Criteria) this;
		}

		public Criteria andScardNumGreaterThanOrEqualTo(String value) {
			addCriterion("scard_num >=", value, "scardNum");
			return (Criteria) this;
		}

		public Criteria andScardNumLessThan(String value) {
			addCriterion("scard_num <", value, "scardNum");
			return (Criteria) this;
		}

		public Criteria andScardNumLessThanOrEqualTo(String value) {
			addCriterion("scard_num <=", value, "scardNum");
			return (Criteria) this;
		}

		public Criteria andScardNumLike(String value) {
			addCriterion("scard_num like", value, "scardNum");
			return (Criteria) this;
		}

		public Criteria andScardNumNotLike(String value) {
			addCriterion("scard_num not like", value, "scardNum");
			return (Criteria) this;
		}

		public Criteria andScardNumIn(List<String> values) {
			addCriterion("scard_num in", values, "scardNum");
			return (Criteria) this;
		}

		public Criteria andScardNumNotIn(List<String> values) {
			addCriterion("scard_num not in", values, "scardNum");
			return (Criteria) this;
		}

		public Criteria andScardNumBetween(String value1, String value2) {
			addCriterion("scard_num between", value1, value2, "scardNum");
			return (Criteria) this;
		}

		public Criteria andScardNumNotBetween(String value1, String value2) {
			addCriterion("scard_num not between", value1, value2, "scardNum");
			return (Criteria) this;
		}

		public Criteria andIcStateIsNull() {
			addCriterion("IC_STATE is null");
			return (Criteria) this;
		}

		public Criteria andIcStateIsNotNull() {
			addCriterion("IC_STATE is not null");
			return (Criteria) this;
		}

		public Criteria andIcStateEqualTo(String value) {
			addCriterion("IC_STATE =", value, "icState");
			return (Criteria) this;
		}

		public Criteria andIcStateNotEqualTo(String value) {
			addCriterion("IC_STATE <>", value, "icState");
			return (Criteria) this;
		}

		public Criteria andIcStateGreaterThan(String value) {
			addCriterion("IC_STATE >", value, "icState");
			return (Criteria) this;
		}

		public Criteria andIcStateGreaterThanOrEqualTo(String value) {
			addCriterion("IC_STATE >=", value, "icState");
			return (Criteria) this;
		}

		public Criteria andIcStateLessThan(String value) {
			addCriterion("IC_STATE <", value, "icState");
			return (Criteria) this;
		}

		public Criteria andIcStateLessThanOrEqualTo(String value) {
			addCriterion("IC_STATE <=", value, "icState");
			return (Criteria) this;
		}

		public Criteria andIcStateLike(String value) {
			addCriterion("IC_STATE like", value, "icState");
			return (Criteria) this;
		}

		public Criteria andIcStateNotLike(String value) {
			addCriterion("IC_STATE not like", value, "icState");
			return (Criteria) this;
		}

		public Criteria andIcStateIn(List<String> values) {
			addCriterion("IC_STATE in", values, "icState");
			return (Criteria) this;
		}

		public Criteria andIcStateNotIn(List<String> values) {
			addCriterion("IC_STATE not in", values, "icState");
			return (Criteria) this;
		}

		public Criteria andIcStateBetween(String value1, String value2) {
			addCriterion("IC_STATE between", value1, value2, "icState");
			return (Criteria) this;
		}

		public Criteria andIcStateNotBetween(String value1, String value2) {
			addCriterion("IC_STATE not between", value1, value2, "icState");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table device_model_idc_info
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_model_idc_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 14 15:35:49 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}