package com.hiaward.cl.oms.entity;

import java.util.Date;

public class DeviceFaultInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_fault_info.FAULT_NO
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	private String faultNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_fault_info.DEVICE_NO
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	private String deviceNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_fault_info.FAULT_CAUSE
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	private String faultCause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_fault_info.START_TIME
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_fault_info.END_TIME
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_fault_info.CONT_TIME
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	private String contTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_fault_info.REMARK
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_fault_info.FAULT_NO
	 * @return  the value of device_fault_info.FAULT_NO
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public String getFaultNo() {
		return faultNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_fault_info.FAULT_NO
	 * @param faultNo  the value for device_fault_info.FAULT_NO
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public void setFaultNo(String faultNo) {
		this.faultNo = faultNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_fault_info.DEVICE_NO
	 * @return  the value of device_fault_info.DEVICE_NO
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public String getDeviceNo() {
		return deviceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_fault_info.DEVICE_NO
	 * @param deviceNo  the value for device_fault_info.DEVICE_NO
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public void setDeviceNo(String deviceNo) {
		this.deviceNo = deviceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_fault_info.FAULT_CAUSE
	 * @return  the value of device_fault_info.FAULT_CAUSE
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public String getFaultCause() {
		return faultCause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_fault_info.FAULT_CAUSE
	 * @param faultCause  the value for device_fault_info.FAULT_CAUSE
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public void setFaultCause(String faultCause) {
		this.faultCause = faultCause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_fault_info.START_TIME
	 * @return  the value of device_fault_info.START_TIME
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_fault_info.START_TIME
	 * @param startTime  the value for device_fault_info.START_TIME
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_fault_info.END_TIME
	 * @return  the value of device_fault_info.END_TIME
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_fault_info.END_TIME
	 * @param endTime  the value for device_fault_info.END_TIME
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_fault_info.CONT_TIME
	 * @return  the value of device_fault_info.CONT_TIME
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public String getContTime() {
		return contTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_fault_info.CONT_TIME
	 * @param contTime  the value for device_fault_info.CONT_TIME
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public void setContTime(String contTime) {
		this.contTime = contTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_fault_info.REMARK
	 * @return  the value of device_fault_info.REMARK
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_fault_info.REMARK
	 * @param remark  the value for device_fault_info.REMARK
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}