package com.hiaward.cl.oms.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeviceTradeInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public DeviceTradeInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTradeNoIsNull() {
			addCriterion("TRADE_NO is null");
			return (Criteria) this;
		}

		public Criteria andTradeNoIsNotNull() {
			addCriterion("TRADE_NO is not null");
			return (Criteria) this;
		}

		public Criteria andTradeNoEqualTo(String value) {
			addCriterion("TRADE_NO =", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoNotEqualTo(String value) {
			addCriterion("TRADE_NO <>", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoGreaterThan(String value) {
			addCriterion("TRADE_NO >", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoGreaterThanOrEqualTo(String value) {
			addCriterion("TRADE_NO >=", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoLessThan(String value) {
			addCriterion("TRADE_NO <", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoLessThanOrEqualTo(String value) {
			addCriterion("TRADE_NO <=", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoLike(String value) {
			addCriterion("TRADE_NO like", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoNotLike(String value) {
			addCriterion("TRADE_NO not like", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoIn(List<String> values) {
			addCriterion("TRADE_NO in", values, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoNotIn(List<String> values) {
			addCriterion("TRADE_NO not in", values, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoBetween(String value1, String value2) {
			addCriterion("TRADE_NO between", value1, value2, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoNotBetween(String value1, String value2) {
			addCriterion("TRADE_NO not between", value1, value2, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoIsNull() {
			addCriterion("DEVICE_NO is null");
			return (Criteria) this;
		}

		public Criteria andDeviceNoIsNotNull() {
			addCriterion("DEVICE_NO is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceNoEqualTo(String value) {
			addCriterion("DEVICE_NO =", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotEqualTo(String value) {
			addCriterion("DEVICE_NO <>", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoGreaterThan(String value) {
			addCriterion("DEVICE_NO >", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoGreaterThanOrEqualTo(String value) {
			addCriterion("DEVICE_NO >=", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoLessThan(String value) {
			addCriterion("DEVICE_NO <", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoLessThanOrEqualTo(String value) {
			addCriterion("DEVICE_NO <=", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoLike(String value) {
			addCriterion("DEVICE_NO like", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotLike(String value) {
			addCriterion("DEVICE_NO not like", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoIn(List<String> values) {
			addCriterion("DEVICE_NO in", values, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotIn(List<String> values) {
			addCriterion("DEVICE_NO not in", values, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoBetween(String value1, String value2) {
			addCriterion("DEVICE_NO between", value1, value2, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotBetween(String value1, String value2) {
			addCriterion("DEVICE_NO not between", value1, value2, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andTradeTypeIsNull() {
			addCriterion("TRADE_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andTradeTypeIsNotNull() {
			addCriterion("TRADE_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andTradeTypeEqualTo(String value) {
			addCriterion("TRADE_TYPE =", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeNotEqualTo(String value) {
			addCriterion("TRADE_TYPE <>", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeGreaterThan(String value) {
			addCriterion("TRADE_TYPE >", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeGreaterThanOrEqualTo(String value) {
			addCriterion("TRADE_TYPE >=", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeLessThan(String value) {
			addCriterion("TRADE_TYPE <", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeLessThanOrEqualTo(String value) {
			addCriterion("TRADE_TYPE <=", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeLike(String value) {
			addCriterion("TRADE_TYPE like", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeNotLike(String value) {
			addCriterion("TRADE_TYPE not like", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeIn(List<String> values) {
			addCriterion("TRADE_TYPE in", values, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeNotIn(List<String> values) {
			addCriterion("TRADE_TYPE not in", values, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeBetween(String value1, String value2) {
			addCriterion("TRADE_TYPE between", value1, value2, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeNotBetween(String value1, String value2) {
			addCriterion("TRADE_TYPE not between", value1, value2, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeNumIsNull() {
			addCriterion("TRADE_NUM is null");
			return (Criteria) this;
		}

		public Criteria andTradeNumIsNotNull() {
			addCriterion("TRADE_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andTradeNumEqualTo(String value) {
			addCriterion("TRADE_NUM =", value, "tradeNum");
			return (Criteria) this;
		}

		public Criteria andTradeNumNotEqualTo(String value) {
			addCriterion("TRADE_NUM <>", value, "tradeNum");
			return (Criteria) this;
		}

		public Criteria andTradeNumGreaterThan(String value) {
			addCriterion("TRADE_NUM >", value, "tradeNum");
			return (Criteria) this;
		}

		public Criteria andTradeNumGreaterThanOrEqualTo(String value) {
			addCriterion("TRADE_NUM >=", value, "tradeNum");
			return (Criteria) this;
		}

		public Criteria andTradeNumLessThan(String value) {
			addCriterion("TRADE_NUM <", value, "tradeNum");
			return (Criteria) this;
		}

		public Criteria andTradeNumLessThanOrEqualTo(String value) {
			addCriterion("TRADE_NUM <=", value, "tradeNum");
			return (Criteria) this;
		}

		public Criteria andTradeNumLike(String value) {
			addCriterion("TRADE_NUM like", value, "tradeNum");
			return (Criteria) this;
		}

		public Criteria andTradeNumNotLike(String value) {
			addCriterion("TRADE_NUM not like", value, "tradeNum");
			return (Criteria) this;
		}

		public Criteria andTradeNumIn(List<String> values) {
			addCriterion("TRADE_NUM in", values, "tradeNum");
			return (Criteria) this;
		}

		public Criteria andTradeNumNotIn(List<String> values) {
			addCriterion("TRADE_NUM not in", values, "tradeNum");
			return (Criteria) this;
		}

		public Criteria andTradeNumBetween(String value1, String value2) {
			addCriterion("TRADE_NUM between", value1, value2, "tradeNum");
			return (Criteria) this;
		}

		public Criteria andTradeNumNotBetween(String value1, String value2) {
			addCriterion("TRADE_NUM not between", value1, value2, "tradeNum");
			return (Criteria) this;
		}

		public Criteria andTardeTimeIsNull() {
			addCriterion("TARDE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andTardeTimeIsNotNull() {
			addCriterion("TARDE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andTardeTimeEqualTo(Date value) {
			addCriterion("TARDE_TIME =", value, "tardeTime");
			return (Criteria) this;
		}

		public Criteria andTardeTimeNotEqualTo(Date value) {
			addCriterion("TARDE_TIME <>", value, "tardeTime");
			return (Criteria) this;
		}

		public Criteria andTardeTimeGreaterThan(Date value) {
			addCriterion("TARDE_TIME >", value, "tardeTime");
			return (Criteria) this;
		}

		public Criteria andTardeTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("TARDE_TIME >=", value, "tardeTime");
			return (Criteria) this;
		}

		public Criteria andTardeTimeLessThan(Date value) {
			addCriterion("TARDE_TIME <", value, "tardeTime");
			return (Criteria) this;
		}

		public Criteria andTardeTimeLessThanOrEqualTo(Date value) {
			addCriterion("TARDE_TIME <=", value, "tardeTime");
			return (Criteria) this;
		}

		public Criteria andTardeTimeIn(List<Date> values) {
			addCriterion("TARDE_TIME in", values, "tardeTime");
			return (Criteria) this;
		}

		public Criteria andTardeTimeNotIn(List<Date> values) {
			addCriterion("TARDE_TIME not in", values, "tardeTime");
			return (Criteria) this;
		}

		public Criteria andTardeTimeBetween(Date value1, Date value2) {
			addCriterion("TARDE_TIME between", value1, value2, "tardeTime");
			return (Criteria) this;
		}

		public Criteria andTardeTimeNotBetween(Date value1, Date value2) {
			addCriterion("TARDE_TIME not between", value1, value2, "tardeTime");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("REMARK in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("REMARK not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table device_trade_info
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_trade_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 14 15:35:54 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}