package com.hiaward.cl.oms.entity;

import java.util.Date;

public class DeviceInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_info.DEVICE_NO
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	private String deviceNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_info.IP
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_info.TELLER_NO
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	private String tellerNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_info.SER_NUM
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	private String serNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_info.MANUFACTURER
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	private String manufacturer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_info.DEVICE_TYPE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	private String deviceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_info.DEVICE_MODEL
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	private String deviceModel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_info.DEVICE_STATE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	private String deviceState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_info.SER_STATE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	private String serState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_info.STATE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_info.REG_DATE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	private Date regDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_info.DEVICE_NO
	 * @return  the value of device_info.DEVICE_NO
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public String getDeviceNo() {
		return deviceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_info.DEVICE_NO
	 * @param deviceNo  the value for device_info.DEVICE_NO
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void setDeviceNo(String deviceNo) {
		this.deviceNo = deviceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_info.IP
	 * @return  the value of device_info.IP
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_info.IP
	 * @param ip  the value for device_info.IP
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_info.TELLER_NO
	 * @return  the value of device_info.TELLER_NO
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public String getTellerNo() {
		return tellerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_info.TELLER_NO
	 * @param tellerNo  the value for device_info.TELLER_NO
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void setTellerNo(String tellerNo) {
		this.tellerNo = tellerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_info.SER_NUM
	 * @return  the value of device_info.SER_NUM
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public String getSerNum() {
		return serNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_info.SER_NUM
	 * @param serNum  the value for device_info.SER_NUM
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void setSerNum(String serNum) {
		this.serNum = serNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_info.MANUFACTURER
	 * @return  the value of device_info.MANUFACTURER
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public String getManufacturer() {
		return manufacturer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_info.MANUFACTURER
	 * @param manufacturer  the value for device_info.MANUFACTURER
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_info.DEVICE_TYPE
	 * @return  the value of device_info.DEVICE_TYPE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public String getDeviceType() {
		return deviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_info.DEVICE_TYPE
	 * @param deviceType  the value for device_info.DEVICE_TYPE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_info.DEVICE_MODEL
	 * @return  the value of device_info.DEVICE_MODEL
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public String getDeviceModel() {
		return deviceModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_info.DEVICE_MODEL
	 * @param deviceModel  the value for device_info.DEVICE_MODEL
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void setDeviceModel(String deviceModel) {
		this.deviceModel = deviceModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_info.DEVICE_STATE
	 * @return  the value of device_info.DEVICE_STATE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public String getDeviceState() {
		return deviceState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_info.DEVICE_STATE
	 * @param deviceState  the value for device_info.DEVICE_STATE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void setDeviceState(String deviceState) {
		this.deviceState = deviceState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_info.SER_STATE
	 * @return  the value of device_info.SER_STATE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public String getSerState() {
		return serState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_info.SER_STATE
	 * @param serState  the value for device_info.SER_STATE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void setSerState(String serState) {
		this.serState = serState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_info.STATE
	 * @return  the value of device_info.STATE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_info.STATE
	 * @param state  the value for device_info.STATE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_info.REG_DATE
	 * @return  the value of device_info.REG_DATE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_info.REG_DATE
	 * @param regDate  the value for device_info.REG_DATE
	 * @mbggenerated  Thu Jul 14 15:35:43 CST 2016
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}
}