package com.hiaward.cl.oms.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeviceFaultInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public DeviceFaultInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andFaultNoIsNull() {
			addCriterion("FAULT_NO is null");
			return (Criteria) this;
		}

		public Criteria andFaultNoIsNotNull() {
			addCriterion("FAULT_NO is not null");
			return (Criteria) this;
		}

		public Criteria andFaultNoEqualTo(String value) {
			addCriterion("FAULT_NO =", value, "faultNo");
			return (Criteria) this;
		}

		public Criteria andFaultNoNotEqualTo(String value) {
			addCriterion("FAULT_NO <>", value, "faultNo");
			return (Criteria) this;
		}

		public Criteria andFaultNoGreaterThan(String value) {
			addCriterion("FAULT_NO >", value, "faultNo");
			return (Criteria) this;
		}

		public Criteria andFaultNoGreaterThanOrEqualTo(String value) {
			addCriterion("FAULT_NO >=", value, "faultNo");
			return (Criteria) this;
		}

		public Criteria andFaultNoLessThan(String value) {
			addCriterion("FAULT_NO <", value, "faultNo");
			return (Criteria) this;
		}

		public Criteria andFaultNoLessThanOrEqualTo(String value) {
			addCriterion("FAULT_NO <=", value, "faultNo");
			return (Criteria) this;
		}

		public Criteria andFaultNoLike(String value) {
			addCriterion("FAULT_NO like", value, "faultNo");
			return (Criteria) this;
		}

		public Criteria andFaultNoNotLike(String value) {
			addCriterion("FAULT_NO not like", value, "faultNo");
			return (Criteria) this;
		}

		public Criteria andFaultNoIn(List<String> values) {
			addCriterion("FAULT_NO in", values, "faultNo");
			return (Criteria) this;
		}

		public Criteria andFaultNoNotIn(List<String> values) {
			addCriterion("FAULT_NO not in", values, "faultNo");
			return (Criteria) this;
		}

		public Criteria andFaultNoBetween(String value1, String value2) {
			addCriterion("FAULT_NO between", value1, value2, "faultNo");
			return (Criteria) this;
		}

		public Criteria andFaultNoNotBetween(String value1, String value2) {
			addCriterion("FAULT_NO not between", value1, value2, "faultNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoIsNull() {
			addCriterion("DEVICE_NO is null");
			return (Criteria) this;
		}

		public Criteria andDeviceNoIsNotNull() {
			addCriterion("DEVICE_NO is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceNoEqualTo(String value) {
			addCriterion("DEVICE_NO =", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotEqualTo(String value) {
			addCriterion("DEVICE_NO <>", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoGreaterThan(String value) {
			addCriterion("DEVICE_NO >", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoGreaterThanOrEqualTo(String value) {
			addCriterion("DEVICE_NO >=", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoLessThan(String value) {
			addCriterion("DEVICE_NO <", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoLessThanOrEqualTo(String value) {
			addCriterion("DEVICE_NO <=", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoLike(String value) {
			addCriterion("DEVICE_NO like", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotLike(String value) {
			addCriterion("DEVICE_NO not like", value, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoIn(List<String> values) {
			addCriterion("DEVICE_NO in", values, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotIn(List<String> values) {
			addCriterion("DEVICE_NO not in", values, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoBetween(String value1, String value2) {
			addCriterion("DEVICE_NO between", value1, value2, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andDeviceNoNotBetween(String value1, String value2) {
			addCriterion("DEVICE_NO not between", value1, value2, "deviceNo");
			return (Criteria) this;
		}

		public Criteria andFaultCauseIsNull() {
			addCriterion("FAULT_CAUSE is null");
			return (Criteria) this;
		}

		public Criteria andFaultCauseIsNotNull() {
			addCriterion("FAULT_CAUSE is not null");
			return (Criteria) this;
		}

		public Criteria andFaultCauseEqualTo(String value) {
			addCriterion("FAULT_CAUSE =", value, "faultCause");
			return (Criteria) this;
		}

		public Criteria andFaultCauseNotEqualTo(String value) {
			addCriterion("FAULT_CAUSE <>", value, "faultCause");
			return (Criteria) this;
		}

		public Criteria andFaultCauseGreaterThan(String value) {
			addCriterion("FAULT_CAUSE >", value, "faultCause");
			return (Criteria) this;
		}

		public Criteria andFaultCauseGreaterThanOrEqualTo(String value) {
			addCriterion("FAULT_CAUSE >=", value, "faultCause");
			return (Criteria) this;
		}

		public Criteria andFaultCauseLessThan(String value) {
			addCriterion("FAULT_CAUSE <", value, "faultCause");
			return (Criteria) this;
		}

		public Criteria andFaultCauseLessThanOrEqualTo(String value) {
			addCriterion("FAULT_CAUSE <=", value, "faultCause");
			return (Criteria) this;
		}

		public Criteria andFaultCauseLike(String value) {
			addCriterion("FAULT_CAUSE like", value, "faultCause");
			return (Criteria) this;
		}

		public Criteria andFaultCauseNotLike(String value) {
			addCriterion("FAULT_CAUSE not like", value, "faultCause");
			return (Criteria) this;
		}

		public Criteria andFaultCauseIn(List<String> values) {
			addCriterion("FAULT_CAUSE in", values, "faultCause");
			return (Criteria) this;
		}

		public Criteria andFaultCauseNotIn(List<String> values) {
			addCriterion("FAULT_CAUSE not in", values, "faultCause");
			return (Criteria) this;
		}

		public Criteria andFaultCauseBetween(String value1, String value2) {
			addCriterion("FAULT_CAUSE between", value1, value2, "faultCause");
			return (Criteria) this;
		}

		public Criteria andFaultCauseNotBetween(String value1, String value2) {
			addCriterion("FAULT_CAUSE not between", value1, value2, "faultCause");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNull() {
			addCriterion("START_TIME is null");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNotNull() {
			addCriterion("START_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andStartTimeEqualTo(Date value) {
			addCriterion("START_TIME =", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotEqualTo(Date value) {
			addCriterion("START_TIME <>", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThan(Date value) {
			addCriterion("START_TIME >", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("START_TIME >=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThan(Date value) {
			addCriterion("START_TIME <", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThanOrEqualTo(Date value) {
			addCriterion("START_TIME <=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIn(List<Date> values) {
			addCriterion("START_TIME in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotIn(List<Date> values) {
			addCriterion("START_TIME not in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeBetween(Date value1, Date value2) {
			addCriterion("START_TIME between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotBetween(Date value1, Date value2) {
			addCriterion("START_TIME not between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("END_TIME is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("END_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Date value) {
			addCriterion("END_TIME =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Date value) {
			addCriterion("END_TIME <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Date value) {
			addCriterion("END_TIME >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("END_TIME >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Date value) {
			addCriterion("END_TIME <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Date value) {
			addCriterion("END_TIME <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Date> values) {
			addCriterion("END_TIME in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Date> values) {
			addCriterion("END_TIME not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Date value1, Date value2) {
			addCriterion("END_TIME between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Date value1, Date value2) {
			addCriterion("END_TIME not between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andContTimeIsNull() {
			addCriterion("CONT_TIME is null");
			return (Criteria) this;
		}

		public Criteria andContTimeIsNotNull() {
			addCriterion("CONT_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andContTimeEqualTo(String value) {
			addCriterion("CONT_TIME =", value, "contTime");
			return (Criteria) this;
		}

		public Criteria andContTimeNotEqualTo(String value) {
			addCriterion("CONT_TIME <>", value, "contTime");
			return (Criteria) this;
		}

		public Criteria andContTimeGreaterThan(String value) {
			addCriterion("CONT_TIME >", value, "contTime");
			return (Criteria) this;
		}

		public Criteria andContTimeGreaterThanOrEqualTo(String value) {
			addCriterion("CONT_TIME >=", value, "contTime");
			return (Criteria) this;
		}

		public Criteria andContTimeLessThan(String value) {
			addCriterion("CONT_TIME <", value, "contTime");
			return (Criteria) this;
		}

		public Criteria andContTimeLessThanOrEqualTo(String value) {
			addCriterion("CONT_TIME <=", value, "contTime");
			return (Criteria) this;
		}

		public Criteria andContTimeLike(String value) {
			addCriterion("CONT_TIME like", value, "contTime");
			return (Criteria) this;
		}

		public Criteria andContTimeNotLike(String value) {
			addCriterion("CONT_TIME not like", value, "contTime");
			return (Criteria) this;
		}

		public Criteria andContTimeIn(List<String> values) {
			addCriterion("CONT_TIME in", values, "contTime");
			return (Criteria) this;
		}

		public Criteria andContTimeNotIn(List<String> values) {
			addCriterion("CONT_TIME not in", values, "contTime");
			return (Criteria) this;
		}

		public Criteria andContTimeBetween(String value1, String value2) {
			addCriterion("CONT_TIME between", value1, value2, "contTime");
			return (Criteria) this;
		}

		public Criteria andContTimeNotBetween(String value1, String value2) {
			addCriterion("CONT_TIME not between", value1, value2, "contTime");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("REMARK in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("REMARK not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table device_fault_info
	 * @mbggenerated  Wed Jul 27 09:08:01 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_fault_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 14 15:32:54 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}