package com.hiaward.cl.oms.entity;

public class DeviceModelIdcInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_model_idc_info.IDC_NO
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	private String idcNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_model_idc_info.DEVICE_NO
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	private String deviceNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_model_idc_info.IDC_MODEL
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	private String idcModel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_model_idc_info.CARD_STATE
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	private String cardState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_model_idc_info.RECOVERY_BOX
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	private String recoveryBox;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_model_idc_info.Security_support
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	private String securitySupport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_model_idc_info.scard_num
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	private String scardNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_model_idc_info.IC_STATE
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	private String icState;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_model_idc_info.IDC_NO
	 * @return  the value of device_model_idc_info.IDC_NO
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public String getIdcNo() {
		return idcNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_model_idc_info.IDC_NO
	 * @param idcNo  the value for device_model_idc_info.IDC_NO
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public void setIdcNo(String idcNo) {
		this.idcNo = idcNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_model_idc_info.DEVICE_NO
	 * @return  the value of device_model_idc_info.DEVICE_NO
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public String getDeviceNo() {
		return deviceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_model_idc_info.DEVICE_NO
	 * @param deviceNo  the value for device_model_idc_info.DEVICE_NO
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public void setDeviceNo(String deviceNo) {
		this.deviceNo = deviceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_model_idc_info.IDC_MODEL
	 * @return  the value of device_model_idc_info.IDC_MODEL
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public String getIdcModel() {
		return idcModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_model_idc_info.IDC_MODEL
	 * @param idcModel  the value for device_model_idc_info.IDC_MODEL
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public void setIdcModel(String idcModel) {
		this.idcModel = idcModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_model_idc_info.CARD_STATE
	 * @return  the value of device_model_idc_info.CARD_STATE
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public String getCardState() {
		return cardState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_model_idc_info.CARD_STATE
	 * @param cardState  the value for device_model_idc_info.CARD_STATE
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public void setCardState(String cardState) {
		this.cardState = cardState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_model_idc_info.RECOVERY_BOX
	 * @return  the value of device_model_idc_info.RECOVERY_BOX
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public String getRecoveryBox() {
		return recoveryBox;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_model_idc_info.RECOVERY_BOX
	 * @param recoveryBox  the value for device_model_idc_info.RECOVERY_BOX
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public void setRecoveryBox(String recoveryBox) {
		this.recoveryBox = recoveryBox;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_model_idc_info.Security_support
	 * @return  the value of device_model_idc_info.Security_support
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public String getSecuritySupport() {
		return securitySupport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_model_idc_info.Security_support
	 * @param securitySupport  the value for device_model_idc_info.Security_support
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public void setSecuritySupport(String securitySupport) {
		this.securitySupport = securitySupport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_model_idc_info.scard_num
	 * @return  the value of device_model_idc_info.scard_num
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public String getScardNum() {
		return scardNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_model_idc_info.scard_num
	 * @param scardNum  the value for device_model_idc_info.scard_num
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public void setScardNum(String scardNum) {
		this.scardNum = scardNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_model_idc_info.IC_STATE
	 * @return  the value of device_model_idc_info.IC_STATE
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public String getIcState() {
		return icState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_model_idc_info.IC_STATE
	 * @param icState  the value for device_model_idc_info.IC_STATE
	 * @mbggenerated  Thu Jul 14 15:35:49 CST 2016
	 */
	public void setIcState(String icState) {
		this.icState = icState;
	}
}