package com.hiaward.cl.oms.entity;

import java.util.Date;

public class DeviceTradeInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_trade_info.TRADE_NO
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	private String tradeNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_trade_info.DEVICE_NO
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	private String deviceNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_trade_info.TRADE_TYPE
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	private String tradeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_trade_info.TRADE_NUM
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	private String tradeNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_trade_info.TARDE_TIME
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	private Date tardeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_trade_info.REMARK
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_trade_info.TRADE_NO
	 * @return  the value of device_trade_info.TRADE_NO
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public String getTradeNo() {
		return tradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_trade_info.TRADE_NO
	 * @param tradeNo  the value for device_trade_info.TRADE_NO
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public void setTradeNo(String tradeNo) {
		this.tradeNo = tradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_trade_info.DEVICE_NO
	 * @return  the value of device_trade_info.DEVICE_NO
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public String getDeviceNo() {
		return deviceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_trade_info.DEVICE_NO
	 * @param deviceNo  the value for device_trade_info.DEVICE_NO
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public void setDeviceNo(String deviceNo) {
		this.deviceNo = deviceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_trade_info.TRADE_TYPE
	 * @return  the value of device_trade_info.TRADE_TYPE
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public String getTradeType() {
		return tradeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_trade_info.TRADE_TYPE
	 * @param tradeType  the value for device_trade_info.TRADE_TYPE
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_trade_info.TRADE_NUM
	 * @return  the value of device_trade_info.TRADE_NUM
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public String getTradeNum() {
		return tradeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_trade_info.TRADE_NUM
	 * @param tradeNum  the value for device_trade_info.TRADE_NUM
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public void setTradeNum(String tradeNum) {
		this.tradeNum = tradeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_trade_info.TARDE_TIME
	 * @return  the value of device_trade_info.TARDE_TIME
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public Date getTardeTime() {
		return tardeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_trade_info.TARDE_TIME
	 * @param tardeTime  the value for device_trade_info.TARDE_TIME
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public void setTardeTime(Date tardeTime) {
		this.tardeTime = tardeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_trade_info.REMARK
	 * @return  the value of device_trade_info.REMARK
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_trade_info.REMARK
	 * @param remark  the value for device_trade_info.REMARK
	 * @mbggenerated  Thu Jul 14 15:35:54 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}