package com.hiaward.cl.oms.entity;

public class Term {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.termId
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    private Integer termid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.termNum
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    private String termnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.ipAddr
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    private String ipaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.tellerNum
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    private String tellernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.termIndex
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    private String termindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.manufacturer
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    private Integer manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.deviceType
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    private Integer devicetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.termId
     *
     * @return the value of term.termId
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public Integer getTermid() {
        return termid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.termId
     *
     * @param termid the value for term.termId
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public void setTermid(Integer termid) {
        this.termid = termid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.termNum
     *
     * @return the value of term.termNum
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public String getTermnum() {
        return termnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.termNum
     *
     * @param termnum the value for term.termNum
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public void setTermnum(String termnum) {
        this.termnum = termnum == null ? null : termnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.ipAddr
     *
     * @return the value of term.ipAddr
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public String getIpaddr() {
        return ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.ipAddr
     *
     * @param ipaddr the value for term.ipAddr
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr == null ? null : ipaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.tellerNum
     *
     * @return the value of term.tellerNum
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public String getTellernum() {
        return tellernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.tellerNum
     *
     * @param tellernum the value for term.tellerNum
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public void setTellernum(String tellernum) {
        this.tellernum = tellernum == null ? null : tellernum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.termIndex
     *
     * @return the value of term.termIndex
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public String getTermindex() {
        return termindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.termIndex
     *
     * @param termindex the value for term.termIndex
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public void setTermindex(String termindex) {
        this.termindex = termindex == null ? null : termindex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.manufacturer
     *
     * @return the value of term.manufacturer
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public Integer getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.manufacturer
     *
     * @param manufacturer the value for term.manufacturer
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public void setManufacturer(Integer manufacturer) {
        this.manufacturer = manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.deviceType
     *
     * @return the value of term.deviceType
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public Integer getDevicetype() {
        return devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.deviceType
     *
     * @param devicetype the value for term.deviceType
     *
     * @mbggenerated Wed Jul 27 13:36:53 CST 2016
     */
    public void setDevicetype(Integer devicetype) {
        this.devicetype = devicetype;
    }
}