package com.hiaward.cl.oms.entity;

import java.util.Date;

public class UserInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.USER_ID
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.USER_NAME
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.PASSWORD
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.PHONE
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.EMAIL
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.ROLE
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.STATE
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.reg_date
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	private Date regDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.USER_ID
	 * @return  the value of user_info.USER_ID
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.USER_ID
	 * @param userId  the value for user_info.USER_ID
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.USER_NAME
	 * @return  the value of user_info.USER_NAME
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.USER_NAME
	 * @param userName  the value for user_info.USER_NAME
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.PASSWORD
	 * @return  the value of user_info.PASSWORD
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.PASSWORD
	 * @param password  the value for user_info.PASSWORD
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.PHONE
	 * @return  the value of user_info.PHONE
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.PHONE
	 * @param phone  the value for user_info.PHONE
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.EMAIL
	 * @return  the value of user_info.EMAIL
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.EMAIL
	 * @param email  the value for user_info.EMAIL
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.ROLE
	 * @return  the value of user_info.ROLE
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.ROLE
	 * @param role  the value for user_info.ROLE
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public void setRole(String role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.STATE
	 * @return  the value of user_info.STATE
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.STATE
	 * @param state  the value for user_info.STATE
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.reg_date
	 * @return  the value of user_info.reg_date
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.reg_date
	 * @param regDate  the value for user_info.reg_date
	 * @mbggenerated  Thu Jul 14 15:35:57 CST 2016
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}
}