$axure.loadCurrentPage({
  "url":"设备新增_修改.html",
  "generationDate":new Date(1457666638488.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"11e0f35a97d34a0e8597c39f54ba8e6d",
    "type":"Axure:Page",
    "name":"设备新增/修改",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ad349b945090480d955f53353377d5a2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"89f1de4d113440dfb167b5fd2b0eedc4"},
{
          "id":"0e6504e2d9a14228823cbfefab15eab4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":92},
            "size":{
              "width":152,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15ecd852f92a42d080c16783465a2bf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":92},
                "size":{
                  "width":152,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd83276e5552479e93976636ec0cfe4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":334,
              "y":149},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edbf9fa112634781a9cb1a1866ef72f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":334,
                  "y":149},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c3938e4019441ef90e464ede8242926",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":145},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f37e8fdc64294fa7a2bc173c4ce7f370",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":186},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f19404cd26894e39a759df871e208372",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":230},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"95615c94490c40b390faf7ed62fb734d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":188},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f39969cc53ed4b4fa10ea8d77f924295",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":341,
                  "y":188},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b3b130baf0a45bb968e54d2b20d17e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":235},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e00793abde924caea016ac710ad6749a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":235},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ac6c689960a476c96b6f90393c15f01",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":409,
              "y":270},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e1d4eac0458d452c8ecbea68e4e6fb3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":275},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9839738ec27e44a69ab9236ad0fc4642",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":275},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f41604bc25594dccbfef7048320d0f96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":313},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2605ff1a4bb54c71b26ecd1576ebc0d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":313},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40ee72b856e84c598579a939915564c3",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":310},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a5fb5dddbb1f473da04105876062e7cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":354},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64493de6dc0f416fa9883b19f1ac63fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":354},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"078c66fd26694830b252dc4a3abcdb59",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":351},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"cd514ddbb5e041cca452267013873fea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":402},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9df099d92712431bb11ec82fdd270b5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":402},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6e82026d1fe40058c95995b1291fa3d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":400},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02683e941b9340b5b862f24b3f3ab159",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":400},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1543903ec7db4a3884d90e38a03a10dc",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":400},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e46f448f6c9548d29a02de30f7e3cfc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":400},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"04ebce063bc9474a923293f5baa0c950",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":428},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdc387e39ef241829de4eb19cb67c855",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":428},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b606825934ac4dec9e191a9542c01ede",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":426},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61b315770b004f28bce5865068460d2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":426},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"630af37deb90424a95900dc58a011be1",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":460},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b54eabb940ab4e13a2ecf6b8e8de080c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":460},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e2c7a90867114d07b55a90f27b2bb377",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":324,
              "y":151},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2917f47484994ade9dff6df9ada6af7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":324,
                  "y":151},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba885c26963945b09f3a44035a395982",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":333,
              "y":190},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bac3b29a099d48cfb99490a869231f73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":333,
                  "y":190},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"418e94b0067048798ab44175695322c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":311,
              "y":235},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6374860dfbf54008a615273900de8364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":311,
                  "y":235},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98c47c3413974973b000c9908388f405",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":311,
              "y":275},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7272e0d68e6f4126b845ec43bfc2d174",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":311,
                  "y":275},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21c336c885c7468e92bc8234d0201fd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":311,
              "y":313},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9ddc07efafe4c8792be73d18b2f15d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":311,
                  "y":313},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b963846d29c417ea9c92b4463484b12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":311,
              "y":354},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47aabb9b1c024365a5c2eed5935e5074",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":311,
                  "y":354},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc156c712482453c87bdabbad831b2dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":323,
              "y":403},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3e3bdbdb0f54c898c68ef9b9ed8688d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":323,
                  "y":403},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"925756d1f1dc4e589e0066044b8fb86c",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":454},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8248c2f742f4ad58c5c9061b2288521",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":454},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"15d6ea460abe46aebc111e6d2fb4db52",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":510},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设备管理",
                      "target":{
                        "targetType":"page",
                        "url":"设备管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"fcb8b73e4f194a00a87f200cb651df13",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":510},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设备管理",
                      "target":{
                        "targetType":"page",
                        "url":"设备管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "89f1de4d113440dfb167b5fd2b0eedc4":{
      "packageId":"89f1de4d113440dfb167b5fd2b0eedc4",
      "type":"Axure:Master",
      "name":"运管框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0adc278bfa92425e9e2786d3f809b276",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":893,
                "height":56}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"787ce0163c4747369312f2b6f009ccb8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":893,
                    "height":56}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u1.png"}},
{
            "id":"5e601103fc5c429ea4b0f55ca270ce36",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":5},
              "size":{
                "width":129,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ec900fcf14c4b178b50ac1348485b6c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":14,
                    "y":5},
                  "size":{
                    "width":129,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e7cbcd8ace694a2caae7735611c79e9f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":808,
                "y":16},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bc4f3d32e3f04772aa3f94568438fa04",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":808,
                    "y":16},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆",
                        "target":{
                          "targetType":"page",
                          "url":"登陆.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"599d086b9f4745f1bce230deb4196ef3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":55},
              "size":{
                "width":133,
                "height":501}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59a8144323af451fbf67ce1bf096d66e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":55},
                  "size":{
                    "width":133,
                    "height":501}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u7.png"}},
{
            "id":"410fd120c99845bdb039d15d3e43dbb3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":133,
                "y":55},
              "size":{
                "width":760,
                "height":501}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5cdac9759b354cba865ad530310b8858",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":133,
                    "y":55},
                  "size":{
                    "width":760,
                    "height":501}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u9.png"}},
{
            "id":"6d89a34049c44a0e8a9ffa8032279e01",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":216},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"7a305cb13ba54ef793a55a281467e2a3",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":70},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"8c8749361fe4454ab1103bb535a11e2b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":12,
                "y":129},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"d0b9a3e0eaf24d10919d5e417a099698",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":252},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5d2633ad3cba4689b15659bc756b3d18",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":252},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 用户管理",
                        "target":{
                          "targetType":"page",
                          "url":"用户管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"873b5ad8756345e8b8cc33af9fc09e1d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":278},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68235248af15452e87b2843bdb3fb80a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":278},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 设备管理",
                        "target":{
                          "targetType":"page",
                          "url":"设备管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e70a07123bd143b9805a7c0d2ccf2748",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":700,
                "y":14},
              "size":{
                "width":110,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2b2d8b1db7cc46d99862276bea739cf8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":700,
                    "y":14},
                  "size":{
                    "width":110,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b226ef2e05dc4f6bbf7e79f4249fa7f3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":33,
                "y":105},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e7a013f91a3b46bd8d591af19f51e619",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":33,
                    "y":105},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 全部设备",
                        "target":{
                          "targetType":"page",
                          "url":"全部设备.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dc58899d68ae4605804c89dfcdb4a6c9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":163},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82704a61e8634ece8eba19673c869515",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":163},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 设备故障信息",
                        "target":{
                          "targetType":"page",
                          "url":"设备故障信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8e2e444bd66e491dbc261740360ba541",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":26,
                "y":189},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c9971d860c77422eae3db8e1b8568e53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":26,
                    "y":189},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 交易信息统计",
                        "target":{
                          "targetType":"page",
                          "url":"交易信息统计.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "ad349b945090480d955f53353377d5a2":{
      "scriptId":"u0",
      "0adc278bfa92425e9e2786d3f809b276":{
        "scriptId":"u1"},
      "787ce0163c4747369312f2b6f009ccb8":{
        "scriptId":"u2"},
      "5e601103fc5c429ea4b0f55ca270ce36":{
        "scriptId":"u3"},
      "6ec900fcf14c4b178b50ac1348485b6c":{
        "scriptId":"u4"},
      "e7cbcd8ace694a2caae7735611c79e9f":{
        "scriptId":"u5"},
      "bc4f3d32e3f04772aa3f94568438fa04":{
        "scriptId":"u6"},
      "599d086b9f4745f1bce230deb4196ef3":{
        "scriptId":"u7"},
      "59a8144323af451fbf67ce1bf096d66e":{
        "scriptId":"u8"},
      "410fd120c99845bdb039d15d3e43dbb3":{
        "scriptId":"u9"},
      "5cdac9759b354cba865ad530310b8858":{
        "scriptId":"u10"},
      "6d89a34049c44a0e8a9ffa8032279e01":{
        "scriptId":"u11"},
      "7a305cb13ba54ef793a55a281467e2a3":{
        "scriptId":"u12"},
      "8c8749361fe4454ab1103bb535a11e2b":{
        "scriptId":"u13"},
      "d0b9a3e0eaf24d10919d5e417a099698":{
        "scriptId":"u14"},
      "5d2633ad3cba4689b15659bc756b3d18":{
        "scriptId":"u15"},
      "873b5ad8756345e8b8cc33af9fc09e1d":{
        "scriptId":"u16"},
      "68235248af15452e87b2843bdb3fb80a":{
        "scriptId":"u17"},
      "e70a07123bd143b9805a7c0d2ccf2748":{
        "scriptId":"u18"},
      "2b2d8b1db7cc46d99862276bea739cf8":{
        "scriptId":"u19"},
      "b226ef2e05dc4f6bbf7e79f4249fa7f3":{
        "scriptId":"u20"},
      "e7a013f91a3b46bd8d591af19f51e619":{
        "scriptId":"u21"},
      "dc58899d68ae4605804c89dfcdb4a6c9":{
        "scriptId":"u22"},
      "82704a61e8634ece8eba19673c869515":{
        "scriptId":"u23"},
      "8e2e444bd66e491dbc261740360ba541":{
        "scriptId":"u24"},
      "c9971d860c77422eae3db8e1b8568e53":{
        "scriptId":"u25"}},
    "0e6504e2d9a14228823cbfefab15eab4":{
      "scriptId":"u26"},
    "15ecd852f92a42d080c16783465a2bf8":{
      "scriptId":"u27"},
    "cd83276e5552479e93976636ec0cfe4e":{
      "scriptId":"u28"},
    "edbf9fa112634781a9cb1a1866ef72f4":{
      "scriptId":"u29"},
    "7c3938e4019441ef90e464ede8242926":{
      "scriptId":"u30"},
    "f37e8fdc64294fa7a2bc173c4ce7f370":{
      "scriptId":"u31"},
    "f19404cd26894e39a759df871e208372":{
      "scriptId":"u32"},
    "95615c94490c40b390faf7ed62fb734d":{
      "scriptId":"u33"},
    "f39969cc53ed4b4fa10ea8d77f924295":{
      "scriptId":"u34"},
    "0b3b130baf0a45bb968e54d2b20d17e8":{
      "scriptId":"u35"},
    "e00793abde924caea016ac710ad6749a":{
      "scriptId":"u36"},
    "5ac6c689960a476c96b6f90393c15f01":{
      "scriptId":"u37"},
    "e1d4eac0458d452c8ecbea68e4e6fb3e":{
      "scriptId":"u38"},
    "9839738ec27e44a69ab9236ad0fc4642":{
      "scriptId":"u39"},
    "f41604bc25594dccbfef7048320d0f96":{
      "scriptId":"u40"},
    "2605ff1a4bb54c71b26ecd1576ebc0d0":{
      "scriptId":"u41"},
    "40ee72b856e84c598579a939915564c3":{
      "scriptId":"u42"},
    "a5fb5dddbb1f473da04105876062e7cd":{
      "scriptId":"u43"},
    "64493de6dc0f416fa9883b19f1ac63fd":{
      "scriptId":"u44"},
    "078c66fd26694830b252dc4a3abcdb59":{
      "scriptId":"u45"},
    "cd514ddbb5e041cca452267013873fea":{
      "scriptId":"u46"},
    "9df099d92712431bb11ec82fdd270b5d":{
      "scriptId":"u47"},
    "f6e82026d1fe40058c95995b1291fa3d":{
      "scriptId":"u48"},
    "02683e941b9340b5b862f24b3f3ab159":{
      "scriptId":"u49"},
    "1543903ec7db4a3884d90e38a03a10dc":{
      "scriptId":"u50"},
    "e46f448f6c9548d29a02de30f7e3cfc8":{
      "scriptId":"u51"},
    "04ebce063bc9474a923293f5baa0c950":{
      "scriptId":"u52"},
    "fdc387e39ef241829de4eb19cb67c855":{
      "scriptId":"u53"},
    "b606825934ac4dec9e191a9542c01ede":{
      "scriptId":"u54"},
    "61b315770b004f28bce5865068460d2e":{
      "scriptId":"u55"},
    "630af37deb90424a95900dc58a011be1":{
      "scriptId":"u56"},
    "b54eabb940ab4e13a2ecf6b8e8de080c":{
      "scriptId":"u57"},
    "e2c7a90867114d07b55a90f27b2bb377":{
      "scriptId":"u58"},
    "2917f47484994ade9dff6df9ada6af7e":{
      "scriptId":"u59"},
    "ba885c26963945b09f3a44035a395982":{
      "scriptId":"u60"},
    "bac3b29a099d48cfb99490a869231f73":{
      "scriptId":"u61"},
    "418e94b0067048798ab44175695322c5":{
      "scriptId":"u62"},
    "6374860dfbf54008a615273900de8364":{
      "scriptId":"u63"},
    "98c47c3413974973b000c9908388f405":{
      "scriptId":"u64"},
    "7272e0d68e6f4126b845ec43bfc2d174":{
      "scriptId":"u65"},
    "21c336c885c7468e92bc8234d0201fd4":{
      "scriptId":"u66"},
    "c9ddc07efafe4c8792be73d18b2f15d5":{
      "scriptId":"u67"},
    "1b963846d29c417ea9c92b4463484b12":{
      "scriptId":"u68"},
    "47aabb9b1c024365a5c2eed5935e5074":{
      "scriptId":"u69"},
    "cc156c712482453c87bdabbad831b2dd":{
      "scriptId":"u70"},
    "b3e3bdbdb0f54c898c68ef9b9ed8688d":{
      "scriptId":"u71"},
    "925756d1f1dc4e589e0066044b8fb86c":{
      "scriptId":"u72"},
    "d8248c2f742f4ad58c5c9061b2288521":{
      "scriptId":"u73"},
    "15d6ea460abe46aebc111e6d2fb4db52":{
      "scriptId":"u74"},
    "fcb8b73e4f194a00a87f200cb651df13":{
      "scriptId":"u75"}}});