$axure.loadCurrentPage({
  "url":"硬件模块状态.html",
  "generationDate":new Date(1457666637340.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9a141d77e6084f6bb127a4766fba6296",
    "type":"Axure:Page",
    "name":"硬件模块状态",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8554408e484f42a1ab0891f7560317c9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":4}},
          "adaptiveStyles":{
},
          "masterId":"89f1de4d113440dfb167b5fd2b0eedc4"},
{
          "id":"c18ab249a373401cbc0516c2cc903d1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":92},
            "size":{
              "width":169,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfaf3635acb644e9b6913052d9e59fb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":92},
                "size":{
                  "width":169,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70c0f335be0949fdb26073a0d17aed54",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":138},
            "size":{
              "width":200,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9713b1746d8646a591700ae297420d6c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"64207edef91c47b9907de207268396d9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硬件模块状态/u29.png"}},
{
              "id":"1109ec282c1447d7bbb96d2e70fb6097",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"70fda43330f349d3b466d584a12e31c0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硬件模块状态/u29.png"}},
{
              "id":"6fe26b6ec8bd4156990d60ff6c26f159",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a7b98b0098d44f618821088ef60fe369",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硬件模块状态/u29.png"}},
{
              "id":"3acbf5a666fc43a49b47a7154a2e0f68",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"233f43ca7db844438f25a83733c944a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硬件模块状态/u31.png"}},
{
              "id":"6df327607d274397a2e25c9a2adf5c3c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"33349422048144839ab8def84e3698b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硬件模块状态/u31.png"}},
{
              "id":"a3e27afc34c241ba8367abb25e68a598",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"03f4c87cca34488fbb15d0afe0a5b1f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硬件模块状态/u31.png"}},
{
              "id":"c5e013b80be848e4867e46a9d030c2d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1210b2669eb4b889798c7c04295be67",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硬件模块状态/u29.png"}},
{
              "id":"c53c3e168a9d46efb4cde948486676ab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd8718c1eb444c71bb2244530fbabd12",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硬件模块状态/u31.png"}},
{
              "id":"42540c08fbca4d6fbeca1945d42758cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe44d3daa8b34cd9ba3a7601186513af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硬件模块状态/u29.png"}},
{
              "id":"93b7e76e34404d07868689f889d6e2bd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d6dfbbbd12c44e95839165abe0f572f9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硬件模块状态/u31.png"}},
{
              "id":"f9257e0af66e4c6ab30553e5b7f2deb0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a0ec14f9e036486c98a38b536c210d20",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硬件模块状态/u49.png"}},
{
              "id":"36a0564d59364909b345df662447c407",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":150},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1653623d6ffc4d689c2c5cd0f22af81a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":150},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/硬件模块状态/u51.png"}}]},
{
          "id":"ea51910329ac4e639a256ba56cccfb34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":151,
              "y":333},
            "size":{
              "width":740,
              "height":187}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2a7ff85bf1242eda231894f8a68ca6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":151,
                  "y":333},
                "size":{
                  "width":740,
                  "height":187}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12745dc638534a28b90636d51e4eb534",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":444.5,
              "y":510},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全部设备",
                      "target":{
                        "targetType":"page",
                        "url":"全部设备.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "89f1de4d113440dfb167b5fd2b0eedc4":{
      "packageId":"89f1de4d113440dfb167b5fd2b0eedc4",
      "type":"Axure:Master",
      "name":"运管框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0adc278bfa92425e9e2786d3f809b276",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":893,
                "height":56}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"787ce0163c4747369312f2b6f009ccb8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":893,
                    "height":56}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u1.png"}},
{
            "id":"5e601103fc5c429ea4b0f55ca270ce36",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":5},
              "size":{
                "width":129,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ec900fcf14c4b178b50ac1348485b6c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":14,
                    "y":5},
                  "size":{
                    "width":129,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e7cbcd8ace694a2caae7735611c79e9f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":808,
                "y":16},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bc4f3d32e3f04772aa3f94568438fa04",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":808,
                    "y":16},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆",
                        "target":{
                          "targetType":"page",
                          "url":"登陆.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"599d086b9f4745f1bce230deb4196ef3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":55},
              "size":{
                "width":133,
                "height":501}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59a8144323af451fbf67ce1bf096d66e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":55},
                  "size":{
                    "width":133,
                    "height":501}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u7.png"}},
{
            "id":"410fd120c99845bdb039d15d3e43dbb3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":133,
                "y":55},
              "size":{
                "width":760,
                "height":501}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5cdac9759b354cba865ad530310b8858",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":133,
                    "y":55},
                  "size":{
                    "width":760,
                    "height":501}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u9.png"}},
{
            "id":"6d89a34049c44a0e8a9ffa8032279e01",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":216},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"7a305cb13ba54ef793a55a281467e2a3",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":70},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"8c8749361fe4454ab1103bb535a11e2b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":12,
                "y":129},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"d0b9a3e0eaf24d10919d5e417a099698",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":252},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5d2633ad3cba4689b15659bc756b3d18",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":252},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 用户管理",
                        "target":{
                          "targetType":"page",
                          "url":"用户管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"873b5ad8756345e8b8cc33af9fc09e1d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":278},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68235248af15452e87b2843bdb3fb80a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":278},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 设备管理",
                        "target":{
                          "targetType":"page",
                          "url":"设备管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e70a07123bd143b9805a7c0d2ccf2748",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":700,
                "y":14},
              "size":{
                "width":110,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2b2d8b1db7cc46d99862276bea739cf8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":700,
                    "y":14},
                  "size":{
                    "width":110,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b226ef2e05dc4f6bbf7e79f4249fa7f3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":33,
                "y":105},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e7a013f91a3b46bd8d591af19f51e619",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":33,
                    "y":105},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 全部设备",
                        "target":{
                          "targetType":"page",
                          "url":"全部设备.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dc58899d68ae4605804c89dfcdb4a6c9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":163},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82704a61e8634ece8eba19673c869515",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":163},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 设备故障信息",
                        "target":{
                          "targetType":"page",
                          "url":"设备故障信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8e2e444bd66e491dbc261740360ba541",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":26,
                "y":189},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c9971d860c77422eae3db8e1b8568e53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":26,
                    "y":189},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 交易信息统计",
                        "target":{
                          "targetType":"page",
                          "url":"交易信息统计.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "8554408e484f42a1ab0891f7560317c9":{
      "scriptId":"u0",
      "0adc278bfa92425e9e2786d3f809b276":{
        "scriptId":"u1"},
      "787ce0163c4747369312f2b6f009ccb8":{
        "scriptId":"u2"},
      "5e601103fc5c429ea4b0f55ca270ce36":{
        "scriptId":"u3"},
      "6ec900fcf14c4b178b50ac1348485b6c":{
        "scriptId":"u4"},
      "e7cbcd8ace694a2caae7735611c79e9f":{
        "scriptId":"u5"},
      "bc4f3d32e3f04772aa3f94568438fa04":{
        "scriptId":"u6"},
      "599d086b9f4745f1bce230deb4196ef3":{
        "scriptId":"u7"},
      "59a8144323af451fbf67ce1bf096d66e":{
        "scriptId":"u8"},
      "410fd120c99845bdb039d15d3e43dbb3":{
        "scriptId":"u9"},
      "5cdac9759b354cba865ad530310b8858":{
        "scriptId":"u10"},
      "6d89a34049c44a0e8a9ffa8032279e01":{
        "scriptId":"u11"},
      "7a305cb13ba54ef793a55a281467e2a3":{
        "scriptId":"u12"},
      "8c8749361fe4454ab1103bb535a11e2b":{
        "scriptId":"u13"},
      "d0b9a3e0eaf24d10919d5e417a099698":{
        "scriptId":"u14"},
      "5d2633ad3cba4689b15659bc756b3d18":{
        "scriptId":"u15"},
      "873b5ad8756345e8b8cc33af9fc09e1d":{
        "scriptId":"u16"},
      "68235248af15452e87b2843bdb3fb80a":{
        "scriptId":"u17"},
      "e70a07123bd143b9805a7c0d2ccf2748":{
        "scriptId":"u18"},
      "2b2d8b1db7cc46d99862276bea739cf8":{
        "scriptId":"u19"},
      "b226ef2e05dc4f6bbf7e79f4249fa7f3":{
        "scriptId":"u20"},
      "e7a013f91a3b46bd8d591af19f51e619":{
        "scriptId":"u21"},
      "dc58899d68ae4605804c89dfcdb4a6c9":{
        "scriptId":"u22"},
      "82704a61e8634ece8eba19673c869515":{
        "scriptId":"u23"},
      "8e2e444bd66e491dbc261740360ba541":{
        "scriptId":"u24"},
      "c9971d860c77422eae3db8e1b8568e53":{
        "scriptId":"u25"}},
    "c18ab249a373401cbc0516c2cc903d1c":{
      "scriptId":"u26"},
    "bfaf3635acb644e9b6913052d9e59fb1":{
      "scriptId":"u27"},
    "70c0f335be0949fdb26073a0d17aed54":{
      "scriptId":"u28"},
    "9713b1746d8646a591700ae297420d6c":{
      "scriptId":"u29"},
    "64207edef91c47b9907de207268396d9":{
      "scriptId":"u30"},
    "3acbf5a666fc43a49b47a7154a2e0f68":{
      "scriptId":"u31"},
    "233f43ca7db844438f25a83733c944a5":{
      "scriptId":"u32"},
    "1109ec282c1447d7bbb96d2e70fb6097":{
      "scriptId":"u33"},
    "70fda43330f349d3b466d584a12e31c0":{
      "scriptId":"u34"},
    "6df327607d274397a2e25c9a2adf5c3c":{
      "scriptId":"u35"},
    "33349422048144839ab8def84e3698b7":{
      "scriptId":"u36"},
    "6fe26b6ec8bd4156990d60ff6c26f159":{
      "scriptId":"u37"},
    "a7b98b0098d44f618821088ef60fe369":{
      "scriptId":"u38"},
    "a3e27afc34c241ba8367abb25e68a598":{
      "scriptId":"u39"},
    "03f4c87cca34488fbb15d0afe0a5b1f7":{
      "scriptId":"u40"},
    "c5e013b80be848e4867e46a9d030c2d8":{
      "scriptId":"u41"},
    "e1210b2669eb4b889798c7c04295be67":{
      "scriptId":"u42"},
    "c53c3e168a9d46efb4cde948486676ab":{
      "scriptId":"u43"},
    "bd8718c1eb444c71bb2244530fbabd12":{
      "scriptId":"u44"},
    "42540c08fbca4d6fbeca1945d42758cc":{
      "scriptId":"u45"},
    "fe44d3daa8b34cd9ba3a7601186513af":{
      "scriptId":"u46"},
    "93b7e76e34404d07868689f889d6e2bd":{
      "scriptId":"u47"},
    "d6dfbbbd12c44e95839165abe0f572f9":{
      "scriptId":"u48"},
    "f9257e0af66e4c6ab30553e5b7f2deb0":{
      "scriptId":"u49"},
    "a0ec14f9e036486c98a38b536c210d20":{
      "scriptId":"u50"},
    "36a0564d59364909b345df662447c407":{
      "scriptId":"u51"},
    "1653623d6ffc4d689c2c5cd0f22af81a":{
      "scriptId":"u52"},
    "ea51910329ac4e639a256ba56cccfb34":{
      "scriptId":"u53"},
    "c2a7ff85bf1242eda231894f8a68ca6f":{
      "scriptId":"u54"},
    "12745dc638534a28b90636d51e4eb534":{
      "scriptId":"u55"}}});