$axure.loadCurrentPage({
  "url":"设备故障信息.html",
  "generationDate":new Date(1457666637617.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c9eefa5e2b2f47e9970d41c49dbf58d1",
    "type":"Axure:Page",
    "name":"设备故障信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"44fb28f6f7ef411ca72097fdec215bb5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"89f1de4d113440dfb167b5fd2b0eedc4"},
{
          "id":"72d173385f5941fe86ee5e54a58e1e68",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":191},
            "size":{
              "width":710,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eaa9f4bec9b46c1bcf59fec7580430f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":58,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c70b938d85464f0eba78f874bf517059",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":58,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u27.png"}},
{
              "id":"a9911211213f4a1d8b05293dba0a0b68",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":58,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0a4f0fe24b1b4b68b791d8340dd6575c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":58,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u43.png"}},
{
              "id":"319d9bfe8a8f4aa1b1a4a29c064abad5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":58,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ead120e1cfbc49f2be22bdae485c20c6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":58,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u59.png"}},
{
              "id":"d8e730f619014cabb2b700cd4cc7c206",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":58,
                  "y":0},
                "size":{
                  "width":70,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f121bf25884748a6941c7b8d6ad48c51",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":58,
                      "y":0},
                    "size":{
                      "width":70,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u29.png"}},
{
              "id":"4438eaea75d9473982a4c43af7df9a75",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":30},
                "size":{
                  "width":70,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b7a3ee6474d049cebcd5d1fa2f6d391f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":58,
                      "y":30},
                    "size":{
                      "width":70,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u45.png"}},
{
              "id":"d69a2428e3f1428298be90272543711f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":58,
                  "y":66},
                "size":{
                  "width":70,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c28e62ec0de64864995dc2f98a57e2c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":58,
                      "y":66},
                    "size":{
                      "width":70,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u61.png"}},
{
              "id":"8f9de59284c14c2c8a8c1e5b8fac6f52",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":128,
                  "y":0},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2246e5049cbd4abcb6206bf7770dced7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":128,
                      "y":0},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u31.png"}},
{
              "id":"c7ebe7516f9641d181242ff0e61fbf04",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":128,
                  "y":30},
                "size":{
                  "width":115,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"17749d6d5d104c60a24f231a13f9e219",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":128,
                      "y":30},
                    "size":{
                      "width":115,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u47.png"}},
{
              "id":"27bede2f34c64a03ade0ec5cf60dc07e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":128,
                  "y":66},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"85fb8877bd93414ca8596da373426251",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":128,
                      "y":66},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u63.png"}},
{
              "id":"5146646b40dd4ff69e25559d26bd57e3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":243,
                  "y":0},
                "size":{
                  "width":64,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8c429ae282a14a82a66dbf098fb91d7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":243,
                      "y":0},
                    "size":{
                      "width":64,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u33.png"}},
{
              "id":"0f28f797a77747f6bdd9edf6c64b6fd0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":243,
                  "y":30},
                "size":{
                  "width":64,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a8c651ba60a4292b4b96825c9965073",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":243,
                      "y":30},
                    "size":{
                      "width":64,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u49.png"}},
{
              "id":"c4a80050ac054b289bc4549021ae10f1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":243,
                  "y":66},
                "size":{
                  "width":64,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"670ccde7e6a8448b91e8303cc571c816",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":243,
                      "y":66},
                    "size":{
                      "width":64,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u65.png"}},
{
              "id":"d41f6134c45748bdac3e71959718c2e7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":307,
                  "y":0},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f0029b00db914ad6aac0b60f9246c216",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":307,
                      "y":0},
                    "size":{
                      "width":75,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u35.png"}},
{
              "id":"b752f03006f4400182af4882c03b5f00",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":307,
                  "y":30},
                "size":{
                  "width":75,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4b307ff796ff48368868082c520dcfa0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":307,
                      "y":30},
                    "size":{
                      "width":75,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u51.png"}},
{
              "id":"493ff0d1345e4ce4b33c6ea9f29c4fa1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":307,
                  "y":66},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7390f20cc0f14761b3445d349272b73e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":307,
                      "y":66},
                    "size":{
                      "width":75,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u67.png"}},
{
              "id":"41029cc017524f62b62a5077a6f96920",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":382,
                  "y":0},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4de3c4a64534ab59e86535b3e56e40f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":382,
                      "y":0},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u37.png"}},
{
              "id":"8904894a31aa43739101e1a8e3b13f88",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":382,
                  "y":30},
                "size":{
                  "width":102,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5753d31c215c41c382b8b7be8891fbd8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":382,
                      "y":30},
                    "size":{
                      "width":102,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u53.png"}},
{
              "id":"a0974a0b53ac4584b2625f020946da1a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":382,
                  "y":66},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d15c1174baa94fd59cb7bb5ada7e7ee7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":382,
                      "y":66},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u69.png"}},
{
              "id":"3cab631232fe4601a9dc069d6e164bd0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":484,
                  "y":0},
                "size":{
                  "width":96,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eb77e1bc9aee42ffa2fd74c93df9b00c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":484,
                      "y":0},
                    "size":{
                      "width":96,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u39.png"}},
{
              "id":"c4e9d2d03f9a49769dc7c6a9ab52b938",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":484,
                  "y":30},
                "size":{
                  "width":96,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5bd771cce8774d2aa4a829c5d59a35c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":484,
                      "y":30},
                    "size":{
                      "width":96,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u55.png"}},
{
              "id":"56fa0c789ca344ef90af0d77e2ce3fef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":484,
                  "y":66},
                "size":{
                  "width":96,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4854b745b2a4be7a989bcbade8594f9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":484,
                      "y":66},
                    "size":{
                      "width":96,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u71.png"}},
{
              "id":"873ac5ed6af64eabb251e516c93e5002",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":580,
                  "y":0},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55237c58d1db4736a7e84c7f850cb1b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":580,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u41.png"}},
{
              "id":"b5f500ff558c4c83bf27b86750c0bf4d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":580,
                  "y":30},
                "size":{
                  "width":130,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a8c690d108f44942a644673161eb1eec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":580,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u57.png"}},
{
              "id":"80ce26593806460e94ba46f84ad14306",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":580,
                  "y":66},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a8317074829744458b312032a868feda",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":580,
                      "y":66},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备故障信息/u73.png"}}]},
{
          "id":"23b7c79c49ab4e05adda5b81b68a6bba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":82},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"725b92463f2d4c78839ee43549cc653c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":82},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b513f98c81845b7aad663dc4c343ea4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":78},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"95c9fcdfb1fc426e852582b585aab91e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":113},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0af2c19c78a64d7db45192838f403948",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":431,
              "y":78},
            "size":{
              "width":134,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e4e379b473764121ba1b2b991f881471",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":82},
            "size":{
              "width":30,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20221ff0df004bd09c2283bd66d98bab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":391,
                  "y":82},
                "size":{
                  "width":30,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fff24adac4144c9a542ad0025dc48d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":169},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ea1776f66f446a4aad966b621958fd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":169},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d13bb599c3ab41ce83f773a5bf975ccd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":246,
              "y":168},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37341e2113c24ec1bd2feffe2de358b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":246,
                  "y":168},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "89f1de4d113440dfb167b5fd2b0eedc4":{
      "packageId":"89f1de4d113440dfb167b5fd2b0eedc4",
      "type":"Axure:Master",
      "name":"运管框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0adc278bfa92425e9e2786d3f809b276",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":893,
                "height":56}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"787ce0163c4747369312f2b6f009ccb8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":893,
                    "height":56}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u1.png"}},
{
            "id":"5e601103fc5c429ea4b0f55ca270ce36",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":5},
              "size":{
                "width":129,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ec900fcf14c4b178b50ac1348485b6c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":14,
                    "y":5},
                  "size":{
                    "width":129,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e7cbcd8ace694a2caae7735611c79e9f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":808,
                "y":16},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bc4f3d32e3f04772aa3f94568438fa04",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":808,
                    "y":16},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆",
                        "target":{
                          "targetType":"page",
                          "url":"登陆.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"599d086b9f4745f1bce230deb4196ef3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":55},
              "size":{
                "width":133,
                "height":501}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59a8144323af451fbf67ce1bf096d66e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":55},
                  "size":{
                    "width":133,
                    "height":501}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u7.png"}},
{
            "id":"410fd120c99845bdb039d15d3e43dbb3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":133,
                "y":55},
              "size":{
                "width":760,
                "height":501}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5cdac9759b354cba865ad530310b8858",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":133,
                    "y":55},
                  "size":{
                    "width":760,
                    "height":501}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u9.png"}},
{
            "id":"6d89a34049c44a0e8a9ffa8032279e01",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":216},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"7a305cb13ba54ef793a55a281467e2a3",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":70},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"8c8749361fe4454ab1103bb535a11e2b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":12,
                "y":129},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"d0b9a3e0eaf24d10919d5e417a099698",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":252},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5d2633ad3cba4689b15659bc756b3d18",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":252},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 用户管理",
                        "target":{
                          "targetType":"page",
                          "url":"用户管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"873b5ad8756345e8b8cc33af9fc09e1d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":278},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68235248af15452e87b2843bdb3fb80a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":278},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 设备管理",
                        "target":{
                          "targetType":"page",
                          "url":"设备管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e70a07123bd143b9805a7c0d2ccf2748",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":700,
                "y":14},
              "size":{
                "width":110,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2b2d8b1db7cc46d99862276bea739cf8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":700,
                    "y":14},
                  "size":{
                    "width":110,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b226ef2e05dc4f6bbf7e79f4249fa7f3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":33,
                "y":105},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e7a013f91a3b46bd8d591af19f51e619",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":33,
                    "y":105},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 全部设备",
                        "target":{
                          "targetType":"page",
                          "url":"全部设备.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dc58899d68ae4605804c89dfcdb4a6c9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":163},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82704a61e8634ece8eba19673c869515",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":163},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 设备故障信息",
                        "target":{
                          "targetType":"page",
                          "url":"设备故障信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8e2e444bd66e491dbc261740360ba541",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":26,
                "y":189},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c9971d860c77422eae3db8e1b8568e53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":26,
                    "y":189},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 交易信息统计",
                        "target":{
                          "targetType":"page",
                          "url":"交易信息统计.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "44fb28f6f7ef411ca72097fdec215bb5":{
      "scriptId":"u0",
      "0adc278bfa92425e9e2786d3f809b276":{
        "scriptId":"u1"},
      "787ce0163c4747369312f2b6f009ccb8":{
        "scriptId":"u2"},
      "5e601103fc5c429ea4b0f55ca270ce36":{
        "scriptId":"u3"},
      "6ec900fcf14c4b178b50ac1348485b6c":{
        "scriptId":"u4"},
      "e7cbcd8ace694a2caae7735611c79e9f":{
        "scriptId":"u5"},
      "bc4f3d32e3f04772aa3f94568438fa04":{
        "scriptId":"u6"},
      "599d086b9f4745f1bce230deb4196ef3":{
        "scriptId":"u7"},
      "59a8144323af451fbf67ce1bf096d66e":{
        "scriptId":"u8"},
      "410fd120c99845bdb039d15d3e43dbb3":{
        "scriptId":"u9"},
      "5cdac9759b354cba865ad530310b8858":{
        "scriptId":"u10"},
      "6d89a34049c44a0e8a9ffa8032279e01":{
        "scriptId":"u11"},
      "7a305cb13ba54ef793a55a281467e2a3":{
        "scriptId":"u12"},
      "8c8749361fe4454ab1103bb535a11e2b":{
        "scriptId":"u13"},
      "d0b9a3e0eaf24d10919d5e417a099698":{
        "scriptId":"u14"},
      "5d2633ad3cba4689b15659bc756b3d18":{
        "scriptId":"u15"},
      "873b5ad8756345e8b8cc33af9fc09e1d":{
        "scriptId":"u16"},
      "68235248af15452e87b2843bdb3fb80a":{
        "scriptId":"u17"},
      "e70a07123bd143b9805a7c0d2ccf2748":{
        "scriptId":"u18"},
      "2b2d8b1db7cc46d99862276bea739cf8":{
        "scriptId":"u19"},
      "b226ef2e05dc4f6bbf7e79f4249fa7f3":{
        "scriptId":"u20"},
      "e7a013f91a3b46bd8d591af19f51e619":{
        "scriptId":"u21"},
      "dc58899d68ae4605804c89dfcdb4a6c9":{
        "scriptId":"u22"},
      "82704a61e8634ece8eba19673c869515":{
        "scriptId":"u23"},
      "8e2e444bd66e491dbc261740360ba541":{
        "scriptId":"u24"},
      "c9971d860c77422eae3db8e1b8568e53":{
        "scriptId":"u25"}},
    "72d173385f5941fe86ee5e54a58e1e68":{
      "scriptId":"u26"},
    "2eaa9f4bec9b46c1bcf59fec7580430f":{
      "scriptId":"u27"},
    "c70b938d85464f0eba78f874bf517059":{
      "scriptId":"u28"},
    "d8e730f619014cabb2b700cd4cc7c206":{
      "scriptId":"u29"},
    "f121bf25884748a6941c7b8d6ad48c51":{
      "scriptId":"u30"},
    "8f9de59284c14c2c8a8c1e5b8fac6f52":{
      "scriptId":"u31"},
    "2246e5049cbd4abcb6206bf7770dced7":{
      "scriptId":"u32"},
    "5146646b40dd4ff69e25559d26bd57e3":{
      "scriptId":"u33"},
    "8c429ae282a14a82a66dbf098fb91d7e":{
      "scriptId":"u34"},
    "d41f6134c45748bdac3e71959718c2e7":{
      "scriptId":"u35"},
    "f0029b00db914ad6aac0b60f9246c216":{
      "scriptId":"u36"},
    "41029cc017524f62b62a5077a6f96920":{
      "scriptId":"u37"},
    "b4de3c4a64534ab59e86535b3e56e40f":{
      "scriptId":"u38"},
    "3cab631232fe4601a9dc069d6e164bd0":{
      "scriptId":"u39"},
    "eb77e1bc9aee42ffa2fd74c93df9b00c":{
      "scriptId":"u40"},
    "873ac5ed6af64eabb251e516c93e5002":{
      "scriptId":"u41"},
    "55237c58d1db4736a7e84c7f850cb1b7":{
      "scriptId":"u42"},
    "a9911211213f4a1d8b05293dba0a0b68":{
      "scriptId":"u43"},
    "0a4f0fe24b1b4b68b791d8340dd6575c":{
      "scriptId":"u44"},
    "4438eaea75d9473982a4c43af7df9a75":{
      "scriptId":"u45"},
    "b7a3ee6474d049cebcd5d1fa2f6d391f":{
      "scriptId":"u46"},
    "c7ebe7516f9641d181242ff0e61fbf04":{
      "scriptId":"u47"},
    "17749d6d5d104c60a24f231a13f9e219":{
      "scriptId":"u48"},
    "0f28f797a77747f6bdd9edf6c64b6fd0":{
      "scriptId":"u49"},
    "6a8c651ba60a4292b4b96825c9965073":{
      "scriptId":"u50"},
    "b752f03006f4400182af4882c03b5f00":{
      "scriptId":"u51"},
    "4b307ff796ff48368868082c520dcfa0":{
      "scriptId":"u52"},
    "8904894a31aa43739101e1a8e3b13f88":{
      "scriptId":"u53"},
    "5753d31c215c41c382b8b7be8891fbd8":{
      "scriptId":"u54"},
    "c4e9d2d03f9a49769dc7c6a9ab52b938":{
      "scriptId":"u55"},
    "5bd771cce8774d2aa4a829c5d59a35c4":{
      "scriptId":"u56"},
    "b5f500ff558c4c83bf27b86750c0bf4d":{
      "scriptId":"u57"},
    "a8c690d108f44942a644673161eb1eec":{
      "scriptId":"u58"},
    "319d9bfe8a8f4aa1b1a4a29c064abad5":{
      "scriptId":"u59"},
    "ead120e1cfbc49f2be22bdae485c20c6":{
      "scriptId":"u60"},
    "d69a2428e3f1428298be90272543711f":{
      "scriptId":"u61"},
    "c28e62ec0de64864995dc2f98a57e2c5":{
      "scriptId":"u62"},
    "27bede2f34c64a03ade0ec5cf60dc07e":{
      "scriptId":"u63"},
    "85fb8877bd93414ca8596da373426251":{
      "scriptId":"u64"},
    "c4a80050ac054b289bc4549021ae10f1":{
      "scriptId":"u65"},
    "670ccde7e6a8448b91e8303cc571c816":{
      "scriptId":"u66"},
    "493ff0d1345e4ce4b33c6ea9f29c4fa1":{
      "scriptId":"u67"},
    "7390f20cc0f14761b3445d349272b73e":{
      "scriptId":"u68"},
    "a0974a0b53ac4584b2625f020946da1a":{
      "scriptId":"u69"},
    "d15c1174baa94fd59cb7bb5ada7e7ee7":{
      "scriptId":"u70"},
    "56fa0c789ca344ef90af0d77e2ce3fef":{
      "scriptId":"u71"},
    "b4854b745b2a4be7a989bcbade8594f9":{
      "scriptId":"u72"},
    "80ce26593806460e94ba46f84ad14306":{
      "scriptId":"u73"},
    "a8317074829744458b312032a868feda":{
      "scriptId":"u74"},
    "23b7c79c49ab4e05adda5b81b68a6bba":{
      "scriptId":"u75"},
    "725b92463f2d4c78839ee43549cc653c":{
      "scriptId":"u76"},
    "0b513f98c81845b7aad663dc4c343ea4":{
      "scriptId":"u77"},
    "95c9fcdfb1fc426e852582b585aab91e":{
      "scriptId":"u78"},
    "0af2c19c78a64d7db45192838f403948":{
      "scriptId":"u79"},
    "e4e379b473764121ba1b2b991f881471":{
      "scriptId":"u80"},
    "20221ff0df004bd09c2283bd66d98bab":{
      "scriptId":"u81"},
    "8fff24adac4144c9a542ad0025dc48d1":{
      "scriptId":"u82"},
    "2ea1776f66f446a4aad966b621958fd1":{
      "scriptId":"u83"},
    "d13bb599c3ab41ce83f773a5bf975ccd":{
      "scriptId":"u84"},
    "37341e2113c24ec1bd2feffe2de358b4":{
      "scriptId":"u85"}}});