$axure.loadCurrentPage({
  "url":"用户管理.html",
  "generationDate":new Date(1457666637983.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e94cefd2688a45d992516f0b9898558b",
    "type":"Axure:Page",
    "name":"用户管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"82b674f756d646019692763d74df7155",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"89f1de4d113440dfb167b5fd2b0eedc4"},
{
          "id":"a34017d61d5e49d09df498edf3e96fdc",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":166},
            "size":{
              "width":720,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bea9c45836e949fc8862d795917318a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":68,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"38314d3e6c234dc1ab6a7c5805ca1f9d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":68,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u27.png"}},
{
              "id":"2379b376efa7404ab481a4ccfd206dd7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":68,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"00c2191fb4404c5cac5d148801ea16ea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":68,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u41.png"}},
{
              "id":"6ec02848e206406194fa0a32df9b91bb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":68,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb19bbe878664e559b6b9fce82ad0b59",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":68,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u55.png"}},
{
              "id":"117f0305eefa4e94866e7cb1955d9b8e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":68,
                  "y":0},
                "size":{
                  "width":84,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b660a45902e455c8f5d18375e42d4d6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":68,
                      "y":0},
                    "size":{
                      "width":84,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u29.png"}},
{
              "id":"aaed179ca74e4d79a74466f17930c927",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":68,
                  "y":30},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bbf4c9986afe434cb20f1d0c4d50f879",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":68,
                      "y":30},
                    "size":{
                      "width":84,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/全部设备/u39.png"}},
{
              "id":"e8cb25924f8a4bd19f6d4f26decd5fd1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":68,
                  "y":66},
                "size":{
                  "width":84,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"111be2b0255c4b04afa2c2cf25129730",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":68,
                      "y":66},
                    "size":{
                      "width":84,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u57.png"}},
{
              "id":"b65329bfc33e4b5ca9fa11c3a2ac49fa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":152,
                  "y":0},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f6f8504b41d64cb9bbfa60878ea3377a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":152,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u31.png"}},
{
              "id":"d9272a98d6534f609b6a057893ccc0af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":152,
                  "y":30},
                "size":{
                  "width":80,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ad7b05e31adc44589dbe5fd374181165",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":152,
                      "y":30},
                    "size":{
                      "width":80,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u45.png"}},
{
              "id":"88a6c383d2f240d5940f21c05bdb5fdd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":152,
                  "y":66},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c220414bee94b46a78028fabaaf1a18",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":152,
                      "y":66},
                    "size":{
                      "width":80,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u59.png"}},
{
              "id":"29660c0795d7444a9f66a7f7b005d7db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":232,
                  "y":0},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a96264fc7d74e3eb132c79d151d0793",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":232,
                      "y":0},
                    "size":{
                      "width":110,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u33.png"}},
{
              "id":"7df4c303ed4441ea9e87f536e13a6b7e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":232,
                  "y":30},
                "size":{
                  "width":110,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"75e675ab7e6b4bbcb42254cfb27cfcca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":232,
                      "y":30},
                    "size":{
                      "width":110,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/全部设备/u35.png"}},
{
              "id":"cf792cd88aaa4943b7b49974766df63a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":232,
                  "y":66},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"25d4897d96624126958d78652b2d9926",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":232,
                      "y":66},
                    "size":{
                      "width":110,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u61.png"}},
{
              "id":"db74e06dc5c24d43a4819d9718780919",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":0},
                "size":{
                  "width":159,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e1ebf6f7b884263baedbaf3e8a07625",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":0},
                    "size":{
                      "width":159,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u35.png"}},
{
              "id":"28ce45dc728a41b689bec386d82e433a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":30},
                "size":{
                  "width":159,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eecd8df52def423eb9bc6e7ed7ebae5f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":30},
                    "size":{
                      "width":159,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u49.png"}},
{
              "id":"612671db0c6c4e10b51bb13ba48698ba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":66},
                "size":{
                  "width":159,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"43061f81162e47fab9b6f27fcdabe46b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":66},
                    "size":{
                      "width":159,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u63.png"}},
{
              "id":"c8b75f243b39416596d08c0ad3bbb48b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":501,
                  "y":0},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"24b138616e8e40cda55d7cd246a2aa73",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":501,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u37.png"}},
{
              "id":"f139a013edbf44559396ed693cabccbc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":501,
                  "y":30},
                "size":{
                  "width":125,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5aca523be1414f5297b262ea5275bf81",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":501,
                      "y":30},
                    "size":{
                      "width":125,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u51.png"}},
{
              "id":"d02ab7c4726b44c796568b0a1c10c387",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":501,
                  "y":66},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ffcab70a4e14c6a8ff60acadfba9c56",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":501,
                      "y":66},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u65.png"}},
{
              "id":"7249263e51494786bb955fc6c2314c12",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":626,
                  "y":0},
                "size":{
                  "width":94,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f196f2866d114c67ae0e309cb47567cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":626,
                      "y":0},
                    "size":{
                      "width":94,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u39.png"}},
{
              "id":"6cdd49f317f24663b738887cf7cedfbb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":626,
                  "y":30},
                "size":{
                  "width":94,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ecf6fdb59eb04e719879c9a8af5ce5ab",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":626,
                      "y":30},
                    "size":{
                      "width":94,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u53.png"}},
{
              "id":"6f5be49bd5524efeb9ec078cc318cfd7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":626,
                  "y":66},
                "size":{
                  "width":94,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77a55357a6634b2eb1de891bda4dabf3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":626,
                      "y":66},
                    "size":{
                      "width":94,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u67.png"}}]},
{
          "id":"f3c40d01554a43fd9eabd53216b85ba4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":82},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bee73e3917e457bac410b1d0c0100a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":82},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"136b84ffc36d4c62970ebfb4d55b396c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":77.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"332f9ddb15494d989086f7214faff8b1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":112},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"de23c03524cd43ec9bfbf44fdf84d8d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":502,
              "y":83},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0bb0e86fbf44606ab2fdfc8945faee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":502,
                  "y":83},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8d13018bcd74200b7e74fbd121661c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":812,
              "y":204},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15bca4b38b344a44826b0a15ac033d1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":812,
                  "y":204},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户新增/修改",
                      "target":{
                        "targetType":"page",
                        "url":"用户新增_修改.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aaad5477202d4c0eac1dff20d41d4458",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":853,
              "y":204},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15cb18cd9b714ad589a4b92fce496f51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":853,
                  "y":204},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3868777179df459f94524047cf822992",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":566,
              "y":78},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"625a746aa77342ecad3b1e19ca22bab1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":131},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户新增/修改",
                      "target":{
                        "targetType":"page",
                        "url":"用户新增_修改.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "89f1de4d113440dfb167b5fd2b0eedc4":{
      "packageId":"89f1de4d113440dfb167b5fd2b0eedc4",
      "type":"Axure:Master",
      "name":"运管框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0adc278bfa92425e9e2786d3f809b276",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":893,
                "height":56}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"787ce0163c4747369312f2b6f009ccb8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":893,
                    "height":56}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u1.png"}},
{
            "id":"5e601103fc5c429ea4b0f55ca270ce36",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":5},
              "size":{
                "width":129,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ec900fcf14c4b178b50ac1348485b6c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":14,
                    "y":5},
                  "size":{
                    "width":129,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e7cbcd8ace694a2caae7735611c79e9f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":808,
                "y":16},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bc4f3d32e3f04772aa3f94568438fa04",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":808,
                    "y":16},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆",
                        "target":{
                          "targetType":"page",
                          "url":"登陆.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"599d086b9f4745f1bce230deb4196ef3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":55},
              "size":{
                "width":133,
                "height":501}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59a8144323af451fbf67ce1bf096d66e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":55},
                  "size":{
                    "width":133,
                    "height":501}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u7.png"}},
{
            "id":"410fd120c99845bdb039d15d3e43dbb3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":133,
                "y":55},
              "size":{
                "width":760,
                "height":501}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5cdac9759b354cba865ad530310b8858",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":133,
                    "y":55},
                  "size":{
                    "width":760,
                    "height":501}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u9.png"}},
{
            "id":"6d89a34049c44a0e8a9ffa8032279e01",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":216},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"7a305cb13ba54ef793a55a281467e2a3",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":70},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"8c8749361fe4454ab1103bb535a11e2b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":12,
                "y":129},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"d0b9a3e0eaf24d10919d5e417a099698",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":252},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5d2633ad3cba4689b15659bc756b3d18",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":252},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 用户管理",
                        "target":{
                          "targetType":"page",
                          "url":"用户管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"873b5ad8756345e8b8cc33af9fc09e1d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":278},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68235248af15452e87b2843bdb3fb80a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":278},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 设备管理",
                        "target":{
                          "targetType":"page",
                          "url":"设备管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e70a07123bd143b9805a7c0d2ccf2748",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":700,
                "y":14},
              "size":{
                "width":110,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2b2d8b1db7cc46d99862276bea739cf8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":700,
                    "y":14},
                  "size":{
                    "width":110,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b226ef2e05dc4f6bbf7e79f4249fa7f3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":33,
                "y":105},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e7a013f91a3b46bd8d591af19f51e619",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":33,
                    "y":105},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 全部设备",
                        "target":{
                          "targetType":"page",
                          "url":"全部设备.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dc58899d68ae4605804c89dfcdb4a6c9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":163},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82704a61e8634ece8eba19673c869515",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":163},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 设备故障信息",
                        "target":{
                          "targetType":"page",
                          "url":"设备故障信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8e2e444bd66e491dbc261740360ba541",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":26,
                "y":189},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c9971d860c77422eae3db8e1b8568e53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":26,
                    "y":189},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 交易信息统计",
                        "target":{
                          "targetType":"page",
                          "url":"交易信息统计.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "82b674f756d646019692763d74df7155":{
      "scriptId":"u0",
      "0adc278bfa92425e9e2786d3f809b276":{
        "scriptId":"u1"},
      "787ce0163c4747369312f2b6f009ccb8":{
        "scriptId":"u2"},
      "5e601103fc5c429ea4b0f55ca270ce36":{
        "scriptId":"u3"},
      "6ec900fcf14c4b178b50ac1348485b6c":{
        "scriptId":"u4"},
      "e7cbcd8ace694a2caae7735611c79e9f":{
        "scriptId":"u5"},
      "bc4f3d32e3f04772aa3f94568438fa04":{
        "scriptId":"u6"},
      "599d086b9f4745f1bce230deb4196ef3":{
        "scriptId":"u7"},
      "59a8144323af451fbf67ce1bf096d66e":{
        "scriptId":"u8"},
      "410fd120c99845bdb039d15d3e43dbb3":{
        "scriptId":"u9"},
      "5cdac9759b354cba865ad530310b8858":{
        "scriptId":"u10"},
      "6d89a34049c44a0e8a9ffa8032279e01":{
        "scriptId":"u11"},
      "7a305cb13ba54ef793a55a281467e2a3":{
        "scriptId":"u12"},
      "8c8749361fe4454ab1103bb535a11e2b":{
        "scriptId":"u13"},
      "d0b9a3e0eaf24d10919d5e417a099698":{
        "scriptId":"u14"},
      "5d2633ad3cba4689b15659bc756b3d18":{
        "scriptId":"u15"},
      "873b5ad8756345e8b8cc33af9fc09e1d":{
        "scriptId":"u16"},
      "68235248af15452e87b2843bdb3fb80a":{
        "scriptId":"u17"},
      "e70a07123bd143b9805a7c0d2ccf2748":{
        "scriptId":"u18"},
      "2b2d8b1db7cc46d99862276bea739cf8":{
        "scriptId":"u19"},
      "b226ef2e05dc4f6bbf7e79f4249fa7f3":{
        "scriptId":"u20"},
      "e7a013f91a3b46bd8d591af19f51e619":{
        "scriptId":"u21"},
      "dc58899d68ae4605804c89dfcdb4a6c9":{
        "scriptId":"u22"},
      "82704a61e8634ece8eba19673c869515":{
        "scriptId":"u23"},
      "8e2e444bd66e491dbc261740360ba541":{
        "scriptId":"u24"},
      "c9971d860c77422eae3db8e1b8568e53":{
        "scriptId":"u25"}},
    "a34017d61d5e49d09df498edf3e96fdc":{
      "scriptId":"u26"},
    "bea9c45836e949fc8862d795917318a2":{
      "scriptId":"u27"},
    "38314d3e6c234dc1ab6a7c5805ca1f9d":{
      "scriptId":"u28"},
    "117f0305eefa4e94866e7cb1955d9b8e":{
      "scriptId":"u29"},
    "8b660a45902e455c8f5d18375e42d4d6":{
      "scriptId":"u30"},
    "b65329bfc33e4b5ca9fa11c3a2ac49fa":{
      "scriptId":"u31"},
    "f6f8504b41d64cb9bbfa60878ea3377a":{
      "scriptId":"u32"},
    "29660c0795d7444a9f66a7f7b005d7db":{
      "scriptId":"u33"},
    "4a96264fc7d74e3eb132c79d151d0793":{
      "scriptId":"u34"},
    "db74e06dc5c24d43a4819d9718780919":{
      "scriptId":"u35"},
    "7e1ebf6f7b884263baedbaf3e8a07625":{
      "scriptId":"u36"},
    "c8b75f243b39416596d08c0ad3bbb48b":{
      "scriptId":"u37"},
    "24b138616e8e40cda55d7cd246a2aa73":{
      "scriptId":"u38"},
    "7249263e51494786bb955fc6c2314c12":{
      "scriptId":"u39"},
    "f196f2866d114c67ae0e309cb47567cb":{
      "scriptId":"u40"},
    "2379b376efa7404ab481a4ccfd206dd7":{
      "scriptId":"u41"},
    "00c2191fb4404c5cac5d148801ea16ea":{
      "scriptId":"u42"},
    "aaed179ca74e4d79a74466f17930c927":{
      "scriptId":"u43"},
    "bbf4c9986afe434cb20f1d0c4d50f879":{
      "scriptId":"u44"},
    "d9272a98d6534f609b6a057893ccc0af":{
      "scriptId":"u45"},
    "ad7b05e31adc44589dbe5fd374181165":{
      "scriptId":"u46"},
    "7df4c303ed4441ea9e87f536e13a6b7e":{
      "scriptId":"u47"},
    "75e675ab7e6b4bbcb42254cfb27cfcca":{
      "scriptId":"u48"},
    "28ce45dc728a41b689bec386d82e433a":{
      "scriptId":"u49"},
    "eecd8df52def423eb9bc6e7ed7ebae5f":{
      "scriptId":"u50"},
    "f139a013edbf44559396ed693cabccbc":{
      "scriptId":"u51"},
    "5aca523be1414f5297b262ea5275bf81":{
      "scriptId":"u52"},
    "6cdd49f317f24663b738887cf7cedfbb":{
      "scriptId":"u53"},
    "ecf6fdb59eb04e719879c9a8af5ce5ab":{
      "scriptId":"u54"},
    "6ec02848e206406194fa0a32df9b91bb":{
      "scriptId":"u55"},
    "fb19bbe878664e559b6b9fce82ad0b59":{
      "scriptId":"u56"},
    "e8cb25924f8a4bd19f6d4f26decd5fd1":{
      "scriptId":"u57"},
    "111be2b0255c4b04afa2c2cf25129730":{
      "scriptId":"u58"},
    "88a6c383d2f240d5940f21c05bdb5fdd":{
      "scriptId":"u59"},
    "5c220414bee94b46a78028fabaaf1a18":{
      "scriptId":"u60"},
    "cf792cd88aaa4943b7b49974766df63a":{
      "scriptId":"u61"},
    "25d4897d96624126958d78652b2d9926":{
      "scriptId":"u62"},
    "612671db0c6c4e10b51bb13ba48698ba":{
      "scriptId":"u63"},
    "43061f81162e47fab9b6f27fcdabe46b":{
      "scriptId":"u64"},
    "d02ab7c4726b44c796568b0a1c10c387":{
      "scriptId":"u65"},
    "2ffcab70a4e14c6a8ff60acadfba9c56":{
      "scriptId":"u66"},
    "6f5be49bd5524efeb9ec078cc318cfd7":{
      "scriptId":"u67"},
    "77a55357a6634b2eb1de891bda4dabf3":{
      "scriptId":"u68"},
    "f3c40d01554a43fd9eabd53216b85ba4":{
      "scriptId":"u69"},
    "8bee73e3917e457bac410b1d0c0100a5":{
      "scriptId":"u70"},
    "136b84ffc36d4c62970ebfb4d55b396c":{
      "scriptId":"u71"},
    "332f9ddb15494d989086f7214faff8b1":{
      "scriptId":"u72"},
    "de23c03524cd43ec9bfbf44fdf84d8d0":{
      "scriptId":"u73"},
    "a0bb0e86fbf44606ab2fdfc8945faee0":{
      "scriptId":"u74"},
    "c8d13018bcd74200b7e74fbd121661c9":{
      "scriptId":"u75"},
    "15bca4b38b344a44826b0a15ac033d1b":{
      "scriptId":"u76"},
    "aaad5477202d4c0eac1dff20d41d4458":{
      "scriptId":"u77"},
    "15cb18cd9b714ad589a4b92fce496f51":{
      "scriptId":"u78"},
    "3868777179df459f94524047cf822992":{
      "scriptId":"u79"},
    "625a746aa77342ecad3b1e19ca22bab1":{
      "scriptId":"u80"}}});