$axure.loadCurrentPage({
  "url":"监控模块（首页）.html",
  "generationDate":new Date(1457666637005.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e0afc39a22c040f4b5acae9c04a8103c",
    "type":"Axure:Page",
    "name":"监控模块（首页）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6b63c5e7b013497698917024c009f678",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":4}},
          "adaptiveStyles":{
},
          "masterId":"89f1de4d113440dfb167b5fd2b0eedc4"},
{
          "id":"643d5b7b3c7c43fa99107bca0da70623",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":60},
            "size":{
              "width":730,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17a5a4266de34bf5a69052a459ca875b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":60},
                "size":{
                  "width":730,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/监控模块（首页）/u26.png"}},
{
          "id":"61b494887c564c5e90b564eb8e0dc2f4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":346},
            "size":{
              "width":720,
              "height":196}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf3b0177e5844af59828249af3014019",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":346},
                "size":{
                  "width":720,
                  "height":196}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/监控模块（首页）/u28.png"}}]}},
  "masters":{
    "89f1de4d113440dfb167b5fd2b0eedc4":{
      "packageId":"89f1de4d113440dfb167b5fd2b0eedc4",
      "type":"Axure:Master",
      "name":"运管框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0adc278bfa92425e9e2786d3f809b276",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":893,
                "height":56}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"787ce0163c4747369312f2b6f009ccb8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":893,
                    "height":56}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u1.png"}},
{
            "id":"5e601103fc5c429ea4b0f55ca270ce36",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":5},
              "size":{
                "width":129,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ec900fcf14c4b178b50ac1348485b6c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":14,
                    "y":5},
                  "size":{
                    "width":129,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e7cbcd8ace694a2caae7735611c79e9f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":808,
                "y":16},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bc4f3d32e3f04772aa3f94568438fa04",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":808,
                    "y":16},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆",
                        "target":{
                          "targetType":"page",
                          "url":"登陆.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"599d086b9f4745f1bce230deb4196ef3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":55},
              "size":{
                "width":133,
                "height":501}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59a8144323af451fbf67ce1bf096d66e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":55},
                  "size":{
                    "width":133,
                    "height":501}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u7.png"}},
{
            "id":"410fd120c99845bdb039d15d3e43dbb3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":133,
                "y":55},
              "size":{
                "width":760,
                "height":501}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5cdac9759b354cba865ad530310b8858",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":133,
                    "y":55},
                  "size":{
                    "width":760,
                    "height":501}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/监控模块（首页）/u9.png"}},
{
            "id":"6d89a34049c44a0e8a9ffa8032279e01",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":216},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"7a305cb13ba54ef793a55a281467e2a3",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":14,
                "y":70},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"8c8749361fe4454ab1103bb535a11e2b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":12,
                "y":129},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"d0b9a3e0eaf24d10919d5e417a099698",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":252},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5d2633ad3cba4689b15659bc756b3d18",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":252},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 用户管理",
                        "target":{
                          "targetType":"page",
                          "url":"用户管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"873b5ad8756345e8b8cc33af9fc09e1d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":278},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68235248af15452e87b2843bdb3fb80a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":278},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 设备管理",
                        "target":{
                          "targetType":"page",
                          "url":"设备管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e70a07123bd143b9805a7c0d2ccf2748",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":700,
                "y":14},
              "size":{
                "width":110,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2b2d8b1db7cc46d99862276bea739cf8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":700,
                    "y":14},
                  "size":{
                    "width":110,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b226ef2e05dc4f6bbf7e79f4249fa7f3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":33,
                "y":105},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e7a013f91a3b46bd8d591af19f51e619",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":33,
                    "y":105},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 全部设备",
                        "target":{
                          "targetType":"page",
                          "url":"全部设备.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dc58899d68ae4605804c89dfcdb4a6c9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":28,
                "y":163},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82704a61e8634ece8eba19673c869515",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":28,
                    "y":163},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 设备故障信息",
                        "target":{
                          "targetType":"page",
                          "url":"设备故障信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8e2e444bd66e491dbc261740360ba541",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0000FF,
                "opacity":1},
              "location":{
                "x":26,
                "y":189},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c9971d860c77422eae3db8e1b8568e53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000FF,
                    "opacity":1},
                  "location":{
                    "x":26,
                    "y":189},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 交易信息统计",
                        "target":{
                          "targetType":"page",
                          "url":"交易信息统计.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "6b63c5e7b013497698917024c009f678":{
      "scriptId":"u0",
      "0adc278bfa92425e9e2786d3f809b276":{
        "scriptId":"u1"},
      "787ce0163c4747369312f2b6f009ccb8":{
        "scriptId":"u2"},
      "5e601103fc5c429ea4b0f55ca270ce36":{
        "scriptId":"u3"},
      "6ec900fcf14c4b178b50ac1348485b6c":{
        "scriptId":"u4"},
      "e7cbcd8ace694a2caae7735611c79e9f":{
        "scriptId":"u5"},
      "bc4f3d32e3f04772aa3f94568438fa04":{
        "scriptId":"u6"},
      "599d086b9f4745f1bce230deb4196ef3":{
        "scriptId":"u7"},
      "59a8144323af451fbf67ce1bf096d66e":{
        "scriptId":"u8"},
      "410fd120c99845bdb039d15d3e43dbb3":{
        "scriptId":"u9"},
      "5cdac9759b354cba865ad530310b8858":{
        "scriptId":"u10"},
      "6d89a34049c44a0e8a9ffa8032279e01":{
        "scriptId":"u11"},
      "7a305cb13ba54ef793a55a281467e2a3":{
        "scriptId":"u12"},
      "8c8749361fe4454ab1103bb535a11e2b":{
        "scriptId":"u13"},
      "d0b9a3e0eaf24d10919d5e417a099698":{
        "scriptId":"u14"},
      "5d2633ad3cba4689b15659bc756b3d18":{
        "scriptId":"u15"},
      "873b5ad8756345e8b8cc33af9fc09e1d":{
        "scriptId":"u16"},
      "68235248af15452e87b2843bdb3fb80a":{
        "scriptId":"u17"},
      "e70a07123bd143b9805a7c0d2ccf2748":{
        "scriptId":"u18"},
      "2b2d8b1db7cc46d99862276bea739cf8":{
        "scriptId":"u19"},
      "b226ef2e05dc4f6bbf7e79f4249fa7f3":{
        "scriptId":"u20"},
      "e7a013f91a3b46bd8d591af19f51e619":{
        "scriptId":"u21"},
      "dc58899d68ae4605804c89dfcdb4a6c9":{
        "scriptId":"u22"},
      "82704a61e8634ece8eba19673c869515":{
        "scriptId":"u23"},
      "8e2e444bd66e491dbc261740360ba541":{
        "scriptId":"u24"},
      "c9971d860c77422eae3db8e1b8568e53":{
        "scriptId":"u25"}},
    "643d5b7b3c7c43fa99107bca0da70623":{
      "scriptId":"u26"},
    "17a5a4266de34bf5a69052a459ca875b":{
      "scriptId":"u27"},
    "61b494887c564c5e90b564eb8e0dc2f4":{
      "scriptId":"u28"},
    "bf3b0177e5844af59828249af3014019":{
      "scriptId":"u29"}}});